/**
 * strings.js — 스캐너 UI 문구 사전 (ko · en · ja).
 *
 * 기구는 `/src/i18n.js` 가 갖고, 여기엔 문구만 둔다.
 *
 * ⚠ **여기 값은 정적 문구만이다.** 스캔 결과·URL 같은 외부 문자열을 사전에 섞지 마라 —
 *    `data-i18n-html` 이 innerHTML 을 쓰므로 그 순간 XSS 경로가 된다.
 *    사용자 데이터를 보여주는 자리는 스캐너 쪽에서 textContent 로 넣는다.
 *
 * ⚠ 키를 추가하면 **세 언어 모두** 채운다. 빠지면 한국어로 폴백되어 조용히 섞인다
 *    (`test/scanner-i18n.test.js` 가 누락을 잡는다).
 */

export const SCANNER_STRINGS = {
  ko: {
    'app.label': 'TLcube 스캐너',
    'camera.label': 'TLcube 코드를 비추는 카메라 화면',
    'brand.label': 'TLcube 소개 홈페이지 (새 창)',
    'guide.label': '스캔 가이드',
    'guide.message': 'TLcube 코드를 프레임 안에 맞춰 주세요.',
    'status.preparing': '카메라를 준비하고 있어요.',
    'button.photo': '사진에서 스캔',
    'picker.label': '카메라 렌즈 선택',
    'input.label': '스캔할 사진 선택',
    'footer.intro': '소개',
    'footer.generator': '생성기',
    'lang.label': '언어',

    'gate.title': '카메라를 시작할까요?',
    'gate.message': '카메라 권한을 허용하면 바로 스캔해요.',
    'gate.start': '탭해서 카메라 시작',
    'gate.https.title': 'HTTPS 연결이 필요해요',
    'gate.https.message': 'HTTPS가 아닌 연결에서는 카메라를 사용할 수 없어요. 사진에서 스캔할 수 있어요.',
    'gate.https.start': 'HTTPS에서 카메라 사용',
    'gate.unsupported.title': '카메라를 사용할 수 없어요',
    'gate.unsupported.message': '이 브라우저에서는 카메라 기능을 지원하지 않아요. 사진에서 스캔할 수 있어요.',
    'gate.denied.title': '카메라 권한이 필요해요',
    'gate.denied.message': '브라우저에서 카메라 권한을 허용한 뒤 다시 탭해 주세요.',
    'gate.notfound.title': '카메라를 찾지 못했어요',
    'gate.notfound.message': '카메라 연결을 확인한 뒤 다시 탭하거나 사진에서 스캔해 주세요.',
    'gate.failed.title': '카메라를 열지 못했어요',
    'gate.failed.message': '잠시 후 다시 탭하거나 사진에서 스캔해 주세요.',
    'gate.off.title': '카메라 권한이 꺼져 있어요',
    'gate.off.message': '브라우저 설정에서 카메라 권한을 허용한 뒤 다시 탭해 주세요.',
    'gate.retry': '카메라 다시 시도',

    'status.starting': '카메라를 시작하고 있어요.',
    'status.aim': '코드를 프레임 안에 맞춰 주세요.',
    'status.closer': '코드가 화면에 더 크게 보이도록 가까이 가져가 보세요.',
    'status.tapToStart': '카메라를 시작하려면 화면을 탭해 주세요.',
    'status.noHttps': 'HTTPS 연결이 아니어서 카메라를 사용할 수 없어요.',
    'status.unsupported': '이 브라우저에서는 카메라를 사용할 수 없어요.',
    'status.checkingPhoto': '사진을 확인하고 있어요.',
    'status.photoUnreadable': '사진을 읽지 못했어요. 다른 사진을 선택해 주세요.',
    'status.photoNoResult': '사진에서 결과를 찾지 못했어요. 다른 사진을 선택하거나 카메라를 시작해 주세요.',
    'status.startOrPick': '카메라를 시작하거나 다른 사진을 선택해 주세요.',
    'status.decoded': '코드를 읽었어요.',
    'status.frameError': '프레임을 처리하는 중 문제가 생겼어요. 다시 시작해 주세요.',
    'status.restart': '카메라를 다시 시작해 주세요.',
    'status.tapToContinue': '계속 스캔하려면 화면을 탭해 주세요.',
    'status.startOrPhoto': '카메라를 시작하거나 사진에서 스캔해 주세요.',
    'status.hiddenStopped': '탭을 떠나면서 카메라를 껐어요. 계속하려면 다시 시작해 주세요.',
    'status.hiddenRestart': '탭을 떠나면서 카메라를 껐어요. 다시 시작해 주세요.',

    'result.title': '스캔 결과',
    'result.close': '스캔 결과 닫기',
    'result.generic': '내용을 읽었어요',
    'result.popupBlocked': '브라우저가 자동으로 새 탭을 열지 못했어요. 아래 버튼을 탭해서 열어 주세요.',
    'result.openLink': '링크 열기',
    'result.rescan': '다시 스캔',
    'result.closeButton': '닫기',
    'result.text.title': '텍스트를 읽었어요',
    'result.text.hint': '내용을 확인하거나 복사할 수 있어요.',
    'result.text.field': '내용',
    'result.url.title': '링크를 읽었어요',
    'result.url.opened': '새 탭에서 주소를 열었어요.',
    'result.url.manual': '아래 버튼을 탭해서 주소를 열어 주세요.',
    'result.url.field': '주소',
    'result.wifi.title': 'Wi-Fi 정보를 읽었어요',
    'result.wifi.hint': '웹에서는 Wi-Fi에 바로 연결할 수 없어요. 필요한 값을 각각 복사해 사용해 주세요.',
    'result.wifi.security': '보안 방식',
    'result.wifi.password': '비밀번호',
    'result.card.title': '명함을 읽었어요',
    'result.card.hint': '연락처와 웹사이트를 바로 사용할 수 있어요.',
    'result.card.name': '이름',
    'result.card.org': '소속',
    'result.card.phone': '전화',
    'result.card.email': '이메일',
    'result.card.site': '웹사이트',
    'copy.button': '복사',
    'copy.suffix': ' 복사',
    'copy.done': '복사했어요',
    'copy.doneSuffix': '을(를) 복사했어요.',
    'copy.failSuffix': '을(를) 복사하지 못했어요. 직접 선택해서 복사해 주세요.',
    'value.none': '없음',
  },

  en: {
    'app.label': 'TLcube scanner',
    'camera.label': 'Camera view for scanning a TLcube code',
    'brand.label': 'TLcube overview site (new window)',
    'guide.label': 'Scan guide',
    'guide.message': 'Fit the TLcube code inside the frame.',
    'status.preparing': 'Getting the camera ready.',
    'button.photo': 'Scan from a photo',
    'picker.label': 'Choose camera lens',
    'input.label': 'Choose a photo to scan',
    'footer.intro': 'About',
    'footer.generator': 'Generator',
    'lang.label': 'Language',

    'gate.title': 'Start the camera?',
    'gate.message': 'Allow camera access and scanning starts right away.',
    'gate.start': 'Tap to start the camera',
    'gate.https.title': 'HTTPS is required',
    'gate.https.message': 'The camera is unavailable over a non-HTTPS connection. You can still scan from a photo.',
    'gate.https.start': 'Camera needs HTTPS',
    'gate.unsupported.title': 'Camera unavailable',
    'gate.unsupported.message': 'This browser does not support camera access. You can still scan from a photo.',
    'gate.denied.title': 'Camera permission needed',
    'gate.denied.message': 'Allow camera access in your browser, then tap again.',
    'gate.notfound.title': 'No camera found',
    'gate.notfound.message': 'Check the camera connection and tap again, or scan from a photo.',
    'gate.failed.title': 'Could not open the camera',
    'gate.failed.message': 'Tap again in a moment, or scan from a photo.',
    'gate.off.title': 'Camera permission is off',
    'gate.off.message': 'Allow camera access in your browser settings, then tap again.',
    'gate.retry': 'Try the camera again',

    'status.starting': 'Starting the camera.',
    'status.aim': 'Fit the code inside the frame.',
    'status.closer': 'Move closer so the code appears larger on screen.',
    'status.tapToStart': 'Tap the screen to start the camera.',
    'status.noHttps': 'The camera is unavailable because this is not an HTTPS connection.',
    'status.unsupported': 'This browser cannot use the camera.',
    'status.checkingPhoto': 'Checking the photo.',
    'status.photoUnreadable': 'Could not read that photo. Please choose another one.',
    'status.photoNoResult': 'No code found in that photo. Choose another one or start the camera.',
    'status.startOrPick': 'Start the camera or choose another photo.',
    'status.decoded': 'Code read.',
    'status.frameError': 'Something went wrong while processing the frame. Please start again.',
    'status.restart': 'Please start the camera again.',
    'status.tapToContinue': 'Tap the screen to keep scanning.',
    'status.startOrPhoto': 'Start the camera or scan from a photo.',
    'status.hiddenStopped': 'The camera stopped when you left the tab. Start again to continue.',
    'status.hiddenRestart': 'The camera stopped when you left the tab. Please start it again.',

    'result.title': 'Scan result',
    'result.close': 'Close scan result',
    'result.generic': 'Content read',
    'result.popupBlocked': 'Your browser blocked the new tab. Tap the button below to open it.',
    'result.openLink': 'Open link',
    'result.rescan': 'Scan again',
    'result.closeButton': 'Close',
    'result.text.title': 'Text read',
    'result.text.hint': 'You can review or copy the content.',
    'result.text.field': 'Content',
    'result.url.title': 'Link read',
    'result.url.opened': 'Opened the address in a new tab.',
    'result.url.manual': 'Tap the button below to open the address.',
    'result.url.field': 'Address',
    'result.wifi.title': 'Wi-Fi details read',
    'result.wifi.hint': 'The web cannot join a Wi-Fi network directly. Copy the values you need.',
    'result.wifi.security': 'Security',
    'result.wifi.password': 'Password',
    'result.card.title': 'Contact card read',
    'result.card.hint': 'The contact details and website are ready to use.',
    'result.card.name': 'Name',
    'result.card.org': 'Organisation',
    'result.card.phone': 'Phone',
    'result.card.email': 'Email',
    'result.card.site': 'Website',
    'copy.button': 'Copy',
    'copy.suffix': ' copy',
    'copy.done': 'Copied',
    'copy.doneSuffix': ' copied.',
    'copy.failSuffix': ' could not be copied. Please select it and copy manually.',
    'value.none': 'None',
  },

  ja: {
    'app.label': 'TLcube スキャナ',
    'camera.label': 'TLcube コードを写すカメラ画面',
    'brand.label': 'TLcube 紹介サイト（新しいウィンドウ）',
    'guide.label': 'スキャンガイド',
    'guide.message': 'TLcube コードを枠の中に合わせてください。',
    'status.preparing': 'カメラを準備しています。',
    'button.photo': '写真からスキャン',
    'picker.label': 'カメラレンズを選択',
    'input.label': 'スキャンする写真を選択',
    'footer.intro': '紹介',
    'footer.generator': 'ジェネレータ',
    'lang.label': '言語',

    'gate.title': 'カメラを起動しますか？',
    'gate.message': 'カメラを許可するとすぐにスキャンできます。',
    'gate.start': 'タップしてカメラを起動',
    'gate.https.title': 'HTTPS 接続が必要です',
    'gate.https.message': 'HTTPS でない接続ではカメラを使えません。写真からスキャンできます。',
    'gate.https.start': 'カメラには HTTPS が必要',
    'gate.unsupported.title': 'カメラを使えません',
    'gate.unsupported.message': 'このブラウザはカメラ機能に対応していません。写真からスキャンできます。',
    'gate.denied.title': 'カメラの許可が必要です',
    'gate.denied.message': 'ブラウザでカメラを許可してから、もう一度タップしてください。',
    'gate.notfound.title': 'カメラが見つかりません',
    'gate.notfound.message': 'カメラの接続を確認してもう一度タップするか、写真からスキャンしてください。',
    'gate.failed.title': 'カメラを起動できませんでした',
    'gate.failed.message': '少し待ってもう一度タップするか、写真からスキャンしてください。',
    'gate.off.title': 'カメラの許可がオフです',
    'gate.off.message': 'ブラウザの設定でカメラを許可してから、もう一度タップしてください。',
    'gate.retry': 'カメラを再試行',

    'status.starting': 'カメラを起動しています。',
    'status.aim': 'コードを枠の中に合わせてください。',
    'status.closer': 'コードが大きく写るように近づけてみてください。',
    'status.tapToStart': '画面をタップするとカメラが起動します。',
    'status.noHttps': 'HTTPS 接続ではないため、カメラを使えません。',
    'status.unsupported': 'このブラウザではカメラを使えません。',
    'status.checkingPhoto': '写真を確認しています。',
    'status.photoUnreadable': '写真を読み取れませんでした。別の写真を選んでください。',
    'status.photoNoResult': '写真からコードが見つかりませんでした。別の写真を選ぶか、カメラを起動してください。',
    'status.startOrPick': 'カメラを起動するか、別の写真を選んでください。',
    'status.decoded': 'コードを読み取りました。',
    'status.frameError': 'フレームの処理中に問題が起きました。もう一度起動してください。',
    'status.restart': 'カメラをもう一度起動してください。',
    'status.tapToContinue': '続けてスキャンするには画面をタップしてください。',
    'status.startOrPhoto': 'カメラを起動するか、写真からスキャンしてください。',
    'status.hiddenStopped': 'タブを離れたときにカメラを停止しました。続けるには再度起動してください。',
    'status.hiddenRestart': 'タブを離れたときにカメラを停止しました。もう一度起動してください。',

    'result.title': 'スキャン結果',
    'result.close': 'スキャン結果を閉じる',
    'result.generic': '内容を読み取りました',
    'result.popupBlocked': 'ブラウザが新しいタブを開けませんでした。下のボタンをタップして開いてください。',
    'result.openLink': 'リンクを開く',
    'result.rescan': 'もう一度スキャン',
    'result.closeButton': '閉じる',
    'result.text.title': 'テキストを読み取りました',
    'result.text.hint': '内容の確認やコピーができます。',
    'result.text.field': '内容',
    'result.url.title': 'リンクを読み取りました',
    'result.url.opened': '新しいタブでアドレスを開きました。',
    'result.url.manual': '下のボタンをタップしてアドレスを開いてください。',
    'result.url.field': 'アドレス',
    'result.wifi.title': 'Wi-Fi 情報を読み取りました',
    'result.wifi.hint': 'ウェブから Wi-Fi に直接接続することはできません。必要な値をコピーしてお使いください。',
    'result.wifi.security': 'セキュリティ方式',
    'result.wifi.password': 'パスワード',
    'result.card.title': '名刺を読み取りました',
    'result.card.hint': '連絡先とウェブサイトをそのまま使えます。',
    'result.card.name': '名前',
    'result.card.org': '所属',
    'result.card.phone': '電話',
    'result.card.email': 'メール',
    'result.card.site': 'ウェブサイト',
    'copy.button': 'コピー',
    'copy.suffix': ' をコピー',
    'copy.done': 'コピーしました',
    'copy.doneSuffix': ' をコピーしました。',
    'copy.failSuffix': ' をコピーできませんでした。手動で選択してコピーしてください。',
    'value.none': 'なし',
  },
};
