/**
 * strings.js — 스캐너 UI 문구 사전 (ko · en · ja · fr · it · de · es · pt).
 *
 * 기구는 `/src/i18n.js` 가 갖고, 여기엔 문구만 둔다.
 *
 * ⚠ **여기 값은 정적 문구만이다.** 스캔 결과·URL 같은 외부 문자열을 사전에 섞지 마라 —
 *    `data-i18n-html` 이 innerHTML 을 쓰므로 그 순간 XSS 경로가 된다.
 *    사용자 데이터를 보여주는 자리는 스캐너 쪽에서 textContent 로 넣는다.
 *
 * ⚠ 키를 추가하면 **여덟 언어 모두** 채운다. 빠지면 한국어로 폴백되어 조용히 섞인다
 *    (`test/scanner-i18n.test.js` 가 누락을 잡는다).
 *
 * ## 번역 규약 (2026-08-17, 5언어 확장)
 *
 * 역어는 `test/output/claude-i18n-glossary.md` 정본을 따른다. 존대는 fr `vous` ·
 * de `Sie` · es `usted` · it/pt 표준 UI 체.
 *
 * ⚠ **`copy.*Suffix` 는 성(性) 중립으로 쓴다.** 세 접미사는 `label + suffix` 로 붙는데
 *    앞에 오는 라벨의 성이 언어마다 갈린다(fr `Adresse` 여성 / `Contenu` 남성).
 *    «copiée/copiato/copiada» 처럼 분사를 일치시키면 절반이 틀린 문장이 된다 —
 *    그래서 「— copie effectuée.」 처럼 **명사구**로 끊는다.
 * ⚠ pt 는 **pt-PT 어휘**로 통일한다 (`câmara`·`ecrã`·`definições`·`palavra-passe`).
 *    생성기 사전이 먼저 그렇게 나갔고(`Ecrã`·`Repor`·`descodificação`), 두 표면이
 *    갈리면 같은 사용자가 화면마다 다른 낱말을 본다.
 */

export const SCANNER_STRINGS = {
  ko: {
    'update.ready': '새 버전이 준비됐어요.',
    'update.apply': '지금 적용',
    'app.label': 'TLcube 스캐너',
    'document.title': 'TLcube 스캐너',
    'camera.label': 'TLcube 코드를 비추는 카메라 화면',
    'fps.title': '초당 처리 프레임 (복호 시도 기준)',
    'brand.label': 'TLcube 소개 홈페이지 (새 창)',
    'guide.label': '스캔 가이드',
    'guide.message': 'TLcube 코드를 점 가이드에 맞춰 주세요.',
    'guide.dots': '코드 꼭짓점은 바깥 점에, O 실루엣 육각형은 중간 고리에, 중앙 큐브는 안쪽 점에 맞춰 주세요.',
    'guide.tlcubeOnly': 'QR 및 다른 바코드는 읽히지 않아요.',
    'zoom.in': '확대',
    'zoom.out': '축소',
    'zoom.slider': '확대 배율',
    'zoom.failed': '카메라 확대를 적용하지 못했어요. 화면 가운데를 잘라 대신해요.',
    'status.preparing': '카메라를 준비하고 있어요.',
    'button.photo': '사진에서 스캔',
    'picker.label': '카메라 렌즈 선택',
    'input.label': '스캔할 사진 선택',
    'footer.intro': '소개',
    'footer.generator': '생성기',
    'lang.label': '언어',

    'gate.title': '카메라를 시작할까요?',
    'gate.message': '카메라 권한을 허용하면 바로 스캔해요.',
    'gate.start': '탭해서 카메라 시작',
    'gate.https.title': 'HTTPS 연결이 필요해요',
    'gate.https.message': 'HTTPS가 아닌 연결에서는 카메라를 사용할 수 없어요. 사진에서 스캔할 수 있어요.',
    'gate.https.start': 'HTTPS에서 카메라 사용',
    'gate.unsupported.title': '카메라를 사용할 수 없어요',
    'gate.unsupported.message': '이 브라우저에서는 카메라 기능을 지원하지 않아요. 사진에서 스캔할 수 있어요.',
    'gate.denied.title': '카메라 권한이 필요해요',
    'gate.denied.message': '브라우저에서 카메라 권한을 허용한 뒤 다시 탭해 주세요.',
    'gate.notfound.title': '카메라를 찾지 못했어요',
    'gate.notfound.message': '카메라 연결을 확인한 뒤 다시 탭하거나 사진에서 스캔해 주세요.',
    'gate.failed.title': '카메라를 열지 못했어요',
    'gate.failed.message': '잠시 후 다시 탭하거나 사진에서 스캔해 주세요.',
    'gate.off.title': '카메라 권한이 꺼져 있어요',
    'gate.off.message': '브라우저 설정에서 카메라 권한을 허용한 뒤 다시 탭해 주세요.',
    'gate.retry': '카메라 다시 시도',

    'status.starting': '카메라를 시작하고 있어요.',
    'status.aim': '코드를 점 가이드에 맞춰 주세요.',
    'status.closer': '코드가 화면에 더 크게 보이도록 가까이 가져가 보세요.',
    'status.clipped': '조금 뒤로 — 코드가 잘려요.',
    // 안정 유지 트리거 (2026-08-16): 1.5초 유지가 채워져 가이드-사전 포즈로 다시 읽는 중.
    // 실패하면 곧바로 status.aim 으로 되돌린다 — 이 문구가 눌러앉으면 안내가 아니라 소음이다.
    'status.steadyScan': '화면이 안정됐어요 — 가이드 기준으로 정밀하게 읽어볼게요.',
    'status.tapToStart': '카메라를 시작하려면 화면을 탭해 주세요.',
    'status.noHttps': 'HTTPS 연결이 아니어서 카메라를 사용할 수 없어요.',
    'status.unsupported': '이 브라우저에서는 카메라를 사용할 수 없어요.',
    'status.checkingPhoto': '사진을 확인하고 있어요.',
    'status.photoUnreadable': '사진을 읽지 못했어요. 다른 사진을 선택해 주세요.',
    'status.photoNoResult': '사진에서 결과를 찾지 못했어요. 다른 사진을 선택하거나 카메라를 시작해 주세요.',
    'status.startOrPick': '카메라를 시작하거나 다른 사진을 선택해 주세요.',
    // 토스트는 상태줄과 같은 사건을 «눈에 띄게» 다시 말한다. 그래서 문구는 더 짧다 —
    // 무엇을 해야 하는지(다른 사진 고르기)는 상태줄이 이어서 안내한다.
    'toast.photoNoResult': '사진에서 코드를 찾지 못했어요.',
    'toast.photoUnreadable': '사진을 읽지 못했어요.',
    'status.decoded': '코드를 읽었어요.',
    'status.frameError': '프레임을 처리하는 중 문제가 생겼어요. 다시 시작해 주세요.',
    'status.restart': '카메라를 다시 시작해 주세요.',
    'status.tapToContinue': '계속 스캔하려면 화면을 탭해 주세요.',
    'status.startOrPhoto': '카메라를 시작하거나 사진에서 스캔해 주세요.',
    'status.hiddenStopped': '탭을 떠나면서 카메라를 껐어요. 계속하려면 다시 시작해 주세요.',
    'status.hiddenRestart': '탭을 떠나면서 카메라를 껐어요. 다시 시작해 주세요.',

    'result.title': '스캔 결과',
    'result.close': '스캔 결과 닫기',
    'result.generic': '내용을 읽었어요',
    'result.popupBlocked': '브라우저가 자동으로 새 탭을 열지 못했어요. 아래 버튼을 탭해서 열어 주세요.',
    'result.openLink': '링크 열기',
    'result.rescan': '다시 스캔',
    'result.closeButton': '닫기',
    'result.text.title': '텍스트를 읽었어요',
    'result.text.hint': '내용을 확인하거나 복사할 수 있어요.',
    'result.text.field': '내용',
    'result.url.title': '링크를 읽었어요',
    'result.url.opened': '새 탭에서 주소를 열었어요.',
    'result.url.manual': '아래 버튼을 탭해서 주소를 열어 주세요.',
    'result.url.field': '주소',
    'result.wifi.title': 'Wi-Fi 정보를 읽었어요',
    'result.wifi.hint': '웹에서는 Wi-Fi에 바로 연결할 수 없어요. 필요한 값을 각각 복사해 사용해 주세요.',
    'result.wifi.security': '보안 방식',
    'result.wifi.password': '비밀번호',
    'result.card.title': '명함을 읽었어요',
    'result.card.hint': '연락처와 웹사이트를 바로 사용할 수 있어요.',
    'result.card.name': '이름',
    'result.card.org': '소속',
    'result.card.phone': '전화',
    'result.card.email': '이메일',
    'result.card.site': '웹사이트',
    'copy.button': '복사',
    'copy.suffix': ' 복사',
    'copy.done': '복사했어요',
    'copy.doneSuffix': '을(를) 복사했어요.',
    'copy.failSuffix': '을(를) 복사하지 못했어요. 직접 선택해서 복사해 주세요.',
    'value.none': '없음',
    // 브라우저가 카메라 이름을 안 주면(권한 전) 쓰는 대체 이름. 뒤에 번호가 붙는다.
    'camera.fallback': '카메라',

    'lab.notice.title': '시험판입니다',
    'lab.notice.body': '이 주소는 시험판입니다. 기기·카메라 정보와 축소 이미지(실패·성공 직전·성공의 층화 표본)가 실시간 전송됩니다. 페이로드 내용은 보내지 않습니다. 안정판은 프레임을 기기 안에서만 처리합니다.',
    'lab.expectedArm.label': '기대 로케이터 팔',
    'lab.expectedArm.unknown': '모름',
    'lab.expectedArm.a': 'A (구)',
    'lab.expectedArm.b': 'B (신)',
    'lab.expectedLayout.label': '기대 레이아웃',
    'lab.expectedLayout.unknown': '모름',
    'lab.expectedLayout.v0': 'v0',
    'lab.expectedLayout.v2r2': 'v2r2',
    'lab.expectedLayout.v1r2': 'v1r2',
    'lab.expectedLayout.v0x': 'v0X',
    'lab.expectedLayout.v0xq': 'v0XQ',
    'lab.expectedLayout.v0w': 'v0W',
    'lab.expectedLayout.v0wq': 'v0WQ',
    'lab.expectedLayout.v0w2': 'v0W2',
    'lab.expectedLayout.v0t': 'v0T',
    'lab.expectedLayout.v0ty': 'v0TY',
    'lab.expectedLayout.v0tr': 'v0TR',
    'lab.expectedLayout.v0trq': 'v0TRQ',
    'lab.expectedLayout.v0try': 'v0TRY',
    'lab.expectedFinder.label': '기대 중앙 파인더',
    'lab.expectedFinder.unknown': '모름',
    'lab.expectedFinder.bullseye': '불스아이',
    'lab.expectedFinder.cube-bullseye': '속큐브',
    'lab.expectedFinder.central-cube-3tone': '3톤큐브',
    'lab.expectedFinder.center-qr': 'QR',
    'lab.expectedFinder.pinwheel-3-0101-cw-missing-solid': 'pinwheel',
    'lab.expectedFinder.gap-ring-01-2-1-solid': 'gap-ring',
    'lab.expectedFinder.flower-7-0020-coprime-offset': 'flower',
    'lab.expectedFinder.swirl-2-200': 'swirl',
    'lab.expectedFinder.pinwheel-c2-2-1100-cw': 'pinwheel-c2',
    'lab.expectedFinder.gap-ring-01-2-1-open': 'gap-ring-open',
    'lab.expectedFinder.flower-7-1020-coprime-offset': 'flower-1020',
    'lab.expectedFinder.swirl-c2-5-5-11-both': 'swirl-c2',
    'lab.expectedFinder.tristar-refined-h3': 'tristar',
    'lab.expectedFinder.tree-refined-h3': 'tree',
    'lab.expectedFinder.cats-refined-h3': 'cats',
    'lab.expectedFinder.oak-nitrogen-r2': 'Nitrogen',
    'lab.expectedFinder.oak-aspirin': 'Aspirin',
    'lab.expectedFinder.oak-benzene': 'Benzene',
    'lab.expectedOuter.label': '기대 외곽 파인더 / 자리 예약',
    'lab.expectedOuter.unknown': '모름',
    'lab.expectedOuter.none': '없음',
    'lab.expectedOuter.daehan': 'sagoae',
    'lab.expectedOuter.a-cm': 'A-CM (자리 예약)',
    'lab.expectedOuter.o-cm': 'O-CM (자리 예약)',
    'lab.debug.toggle': '검출 오버레이',
    'lab.daehan.toggle': 'taegeuk + sagoae',
    'lab.expectedTones.label': '기대 톤',
    'lab.expectedTones.unknown': '모름',
    'lab.expectedTones.two': '2톤',
    'lab.expectedTones.three': '3톤',
  },

  en: {
    'update.ready': 'A new version is ready.',
    'update.apply': 'Apply now',
    'app.label': 'TLcube scanner',
    'document.title': 'TLcube scanner',
    'camera.label': 'Camera view for scanning a TLcube code',
    'fps.title': 'Frames processed per second (decode attempts)',
    'brand.label': 'TLcube overview site (new window)',
    'guide.label': 'Scan guide',
    'guide.message': 'Fit the TLcube code to the dot guide.',
    'guide.dots': 'Match the code corners to the outer dots, the O silhouette hexagon to the middle rings, and the central cube to the inner dots.',
    'guide.tlcubeOnly': 'QR codes and other barcodes are not supported.',
    'zoom.in': 'Zoom in',
    'zoom.out': 'Zoom out',
    'zoom.slider': 'Zoom level',
    'zoom.failed': 'Could not apply camera zoom. Cropping the centre instead.',
    'status.preparing': 'Getting the camera ready.',
    'button.photo': 'Scan from a photo',
    'picker.label': 'Choose camera lens',
    'input.label': 'Choose a photo to scan',
    'footer.intro': 'About',
    'footer.generator': 'Generator',
    'lang.label': 'Language',

    'gate.title': 'Start the camera?',
    'gate.message': 'Allow camera access and scanning starts right away.',
    'gate.start': 'Tap to start the camera',
    'gate.https.title': 'HTTPS is required',
    'gate.https.message': 'The camera is unavailable over a non-HTTPS connection. You can still scan from a photo.',
    'gate.https.start': 'Camera needs HTTPS',
    'gate.unsupported.title': 'Camera unavailable',
    'gate.unsupported.message': 'This browser does not support camera access. You can still scan from a photo.',
    'gate.denied.title': 'Camera permission needed',
    'gate.denied.message': 'Allow camera access in your browser, then tap again.',
    'gate.notfound.title': 'No camera found',
    'gate.notfound.message': 'Check the camera connection and tap again, or scan from a photo.',
    'gate.failed.title': 'Could not open the camera',
    'gate.failed.message': 'Tap again in a moment, or scan from a photo.',
    'gate.off.title': 'Camera permission is off',
    'gate.off.message': 'Allow camera access in your browser settings, then tap again.',
    'gate.retry': 'Try the camera again',

    'status.starting': 'Starting the camera.',
    'status.aim': 'Fit the code to the dot guide.',
    'status.closer': 'Move closer so the code appears larger on screen.',
    'status.clipped': 'Move back a little — the code is getting cut off.',
    'status.steadyScan': 'The view is steady — reading precisely against the guide.',
    'status.tapToStart': 'Tap the screen to start the camera.',
    'status.noHttps': 'The camera is unavailable because this is not an HTTPS connection.',
    'status.unsupported': 'This browser cannot use the camera.',
    'status.checkingPhoto': 'Checking the photo.',
    'status.photoUnreadable': 'Could not read that photo. Please choose another one.',
    'status.photoNoResult': 'No code found in that photo. Choose another one or start the camera.',
    'status.startOrPick': 'Start the camera or choose another photo.',
    'toast.photoNoResult': 'No code found in that photo.',
    'toast.photoUnreadable': 'Could not read that photo.',
    'status.decoded': 'Code read.',
    'status.frameError': 'Something went wrong while processing the frame. Please start again.',
    'status.restart': 'Please start the camera again.',
    'status.tapToContinue': 'Tap the screen to keep scanning.',
    'status.startOrPhoto': 'Start the camera or scan from a photo.',
    'status.hiddenStopped': 'The camera stopped when you left the tab. Start again to continue.',
    'status.hiddenRestart': 'The camera stopped when you left the tab. Please start it again.',

    'result.title': 'Scan result',
    'result.close': 'Close scan result',
    'result.generic': 'Content read',
    'result.popupBlocked': 'Your browser blocked the new tab. Tap the button below to open it.',
    'result.openLink': 'Open link',
    'result.rescan': 'Scan again',
    'result.closeButton': 'Close',
    'result.text.title': 'Text read',
    'result.text.hint': 'You can review or copy the content.',
    'result.text.field': 'Content',
    'result.url.title': 'Link read',
    'result.url.opened': 'Opened the address in a new tab.',
    'result.url.manual': 'Tap the button below to open the address.',
    'result.url.field': 'Address',
    'result.wifi.title': 'Wi-Fi details read',
    'result.wifi.hint': 'The web cannot join a Wi-Fi network directly. Copy the values you need.',
    'result.wifi.security': 'Security',
    'result.wifi.password': 'Password',
    'result.card.title': 'Contact card read',
    'result.card.hint': 'The contact details and website are ready to use.',
    'result.card.name': 'Name',
    'result.card.org': 'Organisation',
    'result.card.phone': 'Phone',
    'result.card.email': 'Email',
    'result.card.site': 'Website',
    'copy.button': 'Copy',
    'copy.suffix': ' copy',
    'copy.done': 'Copied',
    'copy.doneSuffix': ' copied.',
    'copy.failSuffix': ' could not be copied. Please select it and copy manually.',
    'value.none': 'None',
    'camera.fallback': 'Camera',

    'lab.notice.title': 'This is the lab build',
    'lab.notice.body': 'This is the lab scanner. Device and camera details, and shrunken frame images (stratified samples of failures, the frame before success, and success), are sent in real time. Payload contents are not sent. The stable scanner processes frames only on the device.',
    'lab.expectedArm.label': 'Expected locator arm',
    'lab.expectedArm.unknown': 'Unknown',
    'lab.expectedArm.a': 'A (old)',
    'lab.expectedArm.b': 'B (new)',
    'lab.expectedLayout.label': 'Expected layout',
    'lab.expectedLayout.unknown': 'Unknown',
    'lab.expectedLayout.v0': 'v0',
    'lab.expectedLayout.v2r2': 'v2r2',
    'lab.expectedLayout.v1r2': 'v1r2',
    'lab.expectedLayout.v0x': 'v0X',
    'lab.expectedLayout.v0xq': 'v0XQ',
    'lab.expectedLayout.v0w': 'v0W',
    'lab.expectedLayout.v0wq': 'v0WQ',
    'lab.expectedLayout.v0w2': 'v0W2',
    'lab.expectedLayout.v0t': 'v0T',
    'lab.expectedLayout.v0ty': 'v0TY',
    'lab.expectedLayout.v0tr': 'v0TR',
    'lab.expectedLayout.v0trq': 'v0TRQ',
    'lab.expectedLayout.v0try': 'v0TRY',
    'lab.expectedFinder.label': 'Expected centre finder',
    'lab.expectedFinder.unknown': 'Unknown',
    'lab.expectedFinder.bullseye': 'Bullseye',
    'lab.expectedFinder.cube-bullseye': 'Cube-bullseye',
    'lab.expectedFinder.central-cube-3tone': '3-tone cube',
    'lab.expectedFinder.center-qr': 'QR',
    'lab.expectedFinder.pinwheel-3-0101-cw-missing-solid': 'pinwheel',
    'lab.expectedFinder.gap-ring-01-2-1-solid': 'gap-ring',
    'lab.expectedFinder.flower-7-0020-coprime-offset': 'flower',
    'lab.expectedFinder.swirl-2-200': 'swirl',
    'lab.expectedFinder.pinwheel-c2-2-1100-cw': 'pinwheel-c2',
    'lab.expectedFinder.gap-ring-01-2-1-open': 'gap-ring-open',
    'lab.expectedFinder.flower-7-1020-coprime-offset': 'flower-1020',
    'lab.expectedFinder.swirl-c2-5-5-11-both': 'swirl-c2',
    'lab.expectedFinder.tristar-refined-h3': 'tristar',
    'lab.expectedFinder.tree-refined-h3': 'tree',
    'lab.expectedFinder.cats-refined-h3': 'cats',
    'lab.expectedFinder.oak-nitrogen-r2': 'Nitrogen',
    'lab.expectedFinder.oak-aspirin': 'Aspirin',
    'lab.expectedFinder.oak-benzene': 'Benzene',
    'lab.expectedOuter.label': 'Expected outer finder / seat reservation',
    'lab.expectedOuter.unknown': 'Unknown',
    'lab.expectedOuter.none': 'None',
    'lab.expectedOuter.daehan': 'sagoae',
    'lab.expectedOuter.a-cm': 'A-CM (seat)',
    'lab.expectedOuter.o-cm': 'O-CM (seat)',
    'lab.debug.toggle': 'Detection overlay',
    'lab.daehan.toggle': 'taegeuk + sagoae',
    'lab.expectedTones.label': 'Expected tones',
    'lab.expectedTones.unknown': 'Unknown',
    'lab.expectedTones.two': '2-tone',
    'lab.expectedTones.three': '3-tone',
  },

  ja: {
    'update.ready': '新しいバージョンが利用できます。',
    'update.apply': '今すぐ適用',
    'app.label': 'TLcube スキャナ',
    'document.title': 'TLcube スキャナ',
    'camera.label': 'TLcube コードを写すカメラ画面',
    'fps.title': '1秒あたりの処理フレーム数（復号試行基準）',
    'brand.label': 'TLcube 紹介サイト（新しいウィンドウ）',
    'guide.label': 'スキャンガイド',
    'guide.message': 'TLcube コードを点ガイドに合わせてください。',
    'guide.dots': 'コードの頂点を外側の点に、O シルエットの六角形を中間のリングに、中央キューブを内側の点に合わせてください。',
    'guide.tlcubeOnly': 'QR コードやその他のバーコードは読み取れません。',
    'zoom.in': '拡大',
    'zoom.out': '縮小',
    'zoom.slider': '拡大倍率',
    'zoom.failed': 'カメラのズームを適用できませんでした。中央を切り出して代わります。',
    'status.preparing': 'カメラを準備しています。',
    'button.photo': '写真からスキャン',
    'picker.label': 'カメラレンズを選択',
    'input.label': 'スキャンする写真を選択',
    'footer.intro': '紹介',
    'footer.generator': 'ジェネレータ',
    'lang.label': '言語',

    'gate.title': 'カメラを起動しますか？',
    'gate.message': 'カメラを許可するとすぐにスキャンできます。',
    'gate.start': 'タップしてカメラを起動',
    'gate.https.title': 'HTTPS 接続が必要です',
    'gate.https.message': 'HTTPS でない接続ではカメラを使えません。写真からスキャンできます。',
    'gate.https.start': 'カメラには HTTPS が必要',
    'gate.unsupported.title': 'カメラを使えません',
    'gate.unsupported.message': 'このブラウザはカメラ機能に対応していません。写真からスキャンできます。',
    'gate.denied.title': 'カメラの許可が必要です',
    'gate.denied.message': 'ブラウザでカメラを許可してから、もう一度タップしてください。',
    'gate.notfound.title': 'カメラが見つかりません',
    'gate.notfound.message': 'カメラの接続を確認してもう一度タップするか、写真からスキャンしてください。',
    'gate.failed.title': 'カメラを起動できませんでした',
    'gate.failed.message': '少し待ってもう一度タップするか、写真からスキャンしてください。',
    'gate.off.title': 'カメラの許可がオフです',
    'gate.off.message': 'ブラウザの設定でカメラを許可してから、もう一度タップしてください。',
    'gate.retry': 'カメラを再試行',

    'status.starting': 'カメラを起動しています。',
    'status.aim': 'コードを点ガイドに合わせてください。',
    'status.closer': 'コードが大きく写るように近づけてみてください。',
    'status.clipped': '少し離れてください — コードが切れています。',
    'status.steadyScan': '画面が安定しました — ガイド基準で精密に読み取ります。',
    'status.tapToStart': '画面をタップするとカメラが起動します。',
    'status.noHttps': 'HTTPS 接続ではないため、カメラを使えません。',
    'status.unsupported': 'このブラウザではカメラを使えません。',
    'status.checkingPhoto': '写真を確認しています。',
    'status.photoUnreadable': '写真を読み取れませんでした。別の写真を選んでください。',
    'status.photoNoResult': '写真からコードが見つかりませんでした。別の写真を選ぶか、カメラを起動してください。',
    'status.startOrPick': 'カメラを起動するか、別の写真を選んでください。',
    'toast.photoNoResult': '写真からコードが見つかりませんでした。',
    'toast.photoUnreadable': '写真を読み取れませんでした。',
    'status.decoded': 'コードを読み取りました。',
    'status.frameError': 'フレームの処理中に問題が起きました。もう一度起動してください。',
    'status.restart': 'カメラをもう一度起動してください。',
    'status.tapToContinue': '続けてスキャンするには画面をタップしてください。',
    'status.startOrPhoto': 'カメラを起動するか、写真からスキャンしてください。',
    'status.hiddenStopped': 'タブを離れたときにカメラを停止しました。続けるには再度起動してください。',
    'status.hiddenRestart': 'タブを離れたときにカメラを停止しました。もう一度起動してください。',

    'result.title': 'スキャン結果',
    'result.close': 'スキャン結果を閉じる',
    'result.generic': '内容を読み取りました',
    'result.popupBlocked': 'ブラウザが新しいタブを開けませんでした。下のボタンをタップして開いてください。',
    'result.openLink': 'リンクを開く',
    'result.rescan': 'もう一度スキャン',
    'result.closeButton': '閉じる',
    'result.text.title': 'テキストを読み取りました',
    'result.text.hint': '内容の確認やコピーができます。',
    'result.text.field': '内容',
    'result.url.title': 'リンクを読み取りました',
    'result.url.opened': '新しいタブでアドレスを開きました。',
    'result.url.manual': '下のボタンをタップしてアドレスを開いてください。',
    'result.url.field': 'アドレス',
    'result.wifi.title': 'Wi-Fi 情報を読み取りました',
    'result.wifi.hint': 'ウェブから Wi-Fi に直接接続することはできません。必要な値をコピーしてお使いください。',
    'result.wifi.security': 'セキュリティ方式',
    'result.wifi.password': 'パスワード',
    'result.card.title': '名刺を読み取りました',
    'result.card.hint': '連絡先とウェブサイトをそのまま使えます。',
    'result.card.name': '名前',
    'result.card.org': '所属',
    'result.card.phone': '電話',
    'result.card.email': 'メール',
    'result.card.site': 'ウェブサイト',
    'copy.button': 'コピー',
    'copy.suffix': ' をコピー',
    'copy.done': 'コピーしました',
    'copy.doneSuffix': ' をコピーしました。',
    'copy.failSuffix': ' をコピーできませんでした。手動で選択してコピーしてください。',
    'value.none': 'なし',
    'camera.fallback': 'カメラ',

    'lab.notice.title': '試用版です',
    'lab.notice.body': 'このアドレスは試用版です。端末・カメラ情報と、フレームの縮小画像（失敗・成功直前・成功の層化標本）がリアルタイムで送信されます。ペイロードの内容は送りません。安定版はフレームを端末の中だけで処理します。',
    'lab.expectedArm.label': '期待ロケーターアーム',
    'lab.expectedArm.unknown': '不明',
    'lab.expectedArm.a': 'A（旧）',
    'lab.expectedArm.b': 'B（新）',
    'lab.expectedLayout.label': '期待レイアウト',
    'lab.expectedLayout.unknown': '不明',
    'lab.expectedLayout.v0': 'v0',
    'lab.expectedLayout.v2r2': 'v2r2',
    'lab.expectedLayout.v1r2': 'v1r2',
    'lab.expectedLayout.v0x': 'v0X',
    'lab.expectedLayout.v0xq': 'v0XQ',
    'lab.expectedLayout.v0w': 'v0W',
    'lab.expectedLayout.v0wq': 'v0WQ',
    'lab.expectedLayout.v0w2': 'v0W2',
    'lab.expectedLayout.v0t': 'v0T',
    'lab.expectedLayout.v0ty': 'v0TY',
    'lab.expectedLayout.v0tr': 'v0TR',
    'lab.expectedLayout.v0trq': 'v0TRQ',
    'lab.expectedLayout.v0try': 'v0TRY',
    'lab.expectedFinder.label': '期待中央ファインダー',
    'lab.expectedFinder.unknown': '不明',
    'lab.expectedFinder.bullseye': 'ブルズアイ',
    'lab.expectedFinder.cube-bullseye': 'キューブ入りブルズアイ',
    'lab.expectedFinder.central-cube-3tone': '3トーンキューブ',
    'lab.expectedFinder.center-qr': 'QR',
    'lab.expectedFinder.pinwheel-3-0101-cw-missing-solid': 'pinwheel',
    'lab.expectedFinder.gap-ring-01-2-1-solid': 'gap-ring',
    'lab.expectedFinder.flower-7-0020-coprime-offset': 'flower',
    'lab.expectedFinder.swirl-2-200': 'swirl',
    'lab.expectedFinder.pinwheel-c2-2-1100-cw': 'pinwheel-c2',
    'lab.expectedFinder.gap-ring-01-2-1-open': 'gap-ring-open',
    'lab.expectedFinder.flower-7-1020-coprime-offset': 'flower-1020',
    'lab.expectedFinder.swirl-c2-5-5-11-both': 'swirl-c2',
    'lab.expectedFinder.tristar-refined-h3': 'tristar',
    'lab.expectedFinder.tree-refined-h3': 'tree',
    'lab.expectedFinder.cats-refined-h3': 'cats',
    'lab.expectedFinder.oak-nitrogen-r2': 'Nitrogen',
    'lab.expectedFinder.oak-aspirin': 'Aspirin',
    'lab.expectedFinder.oak-benzene': 'Benzene',
    'lab.expectedOuter.label': '期待外周ファインダー / 席予約',
    'lab.expectedOuter.unknown': '不明',
    'lab.expectedOuter.none': 'なし',
    'lab.expectedOuter.daehan': 'sagoae',
    'lab.expectedOuter.a-cm': 'A-CM（席予約）',
    'lab.expectedOuter.o-cm': 'O-CM（席予約）',
    'lab.debug.toggle': '検出オーバーレイ',
    'lab.daehan.toggle': 'taegeuk + sagoae',
    'lab.expectedTones.label': '期待トーン',
    'lab.expectedTones.unknown': '不明',
    'lab.expectedTones.two': '2トーン',
    'lab.expectedTones.three': '3トーン',
  },

  fr: {
    'update.ready': 'Une nouvelle version est prête.',
    'update.apply': 'Appliquer maintenant',
    'app.label': 'Scanner TLcube',
    'document.title': 'Scanner TLcube',
    'camera.label': 'Vue caméra pour scanner un code TLcube',
    'fps.title': 'Images traitées par seconde (tentatives de décodage)',
    'brand.label': 'Site de présentation de TLcube (nouvelle fenêtre)',
    'guide.label': 'Guide de scan',
    'guide.message': 'Alignez le code TLcube sur le guide en points.',
    'guide.dots': 'Placez les coins du code sur les points extérieurs, l\'hexagone de la silhouette O sur les anneaux intermédiaires et le cube central sur les points intérieurs.',
    'guide.tlcubeOnly': 'Les codes QR et les autres codes-barres ne sont pas pris en charge.',
    'zoom.in': 'Zoomer',
    'zoom.out': 'Dézoomer',
    'zoom.slider': 'Niveau de zoom',
    'zoom.failed': 'Impossible d\'appliquer le zoom de la caméra. Recadrage au centre à la place.',
    'status.preparing': 'Préparation de la caméra.',
    'button.photo': 'Scanner depuis une photo',
    'picker.label': 'Choisir l\'objectif',
    'input.label': 'Choisir une photo à scanner',
    'footer.intro': 'À propos',
    'footer.generator': 'Générateur',
    'lang.label': 'Langue',

    'gate.title': 'Démarrer la caméra ?',
    'gate.message': 'Autorisez l\'accès à la caméra et le scan démarre immédiatement.',
    'gate.start': 'Touchez pour démarrer la caméra',
    'gate.https.title': 'Une connexion HTTPS est requise',
    'gate.https.message': 'La caméra n\'est pas disponible sur une connexion non HTTPS. Vous pouvez tout de même scanner depuis une photo.',
    'gate.https.start': 'La caméra exige HTTPS',
    'gate.unsupported.title': 'Caméra indisponible',
    'gate.unsupported.message': 'Ce navigateur ne prend pas en charge l\'accès à la caméra. Vous pouvez scanner depuis une photo.',
    'gate.denied.title': 'Autorisation de la caméra requise',
    'gate.denied.message': 'Autorisez l\'accès à la caméra dans votre navigateur, puis touchez à nouveau.',
    'gate.notfound.title': 'Aucune caméra trouvée',
    'gate.notfound.message': 'Vérifiez la connexion de la caméra puis touchez à nouveau, ou scannez depuis une photo.',
    'gate.failed.title': 'Impossible d\'ouvrir la caméra',
    'gate.failed.message': 'Réessayez dans un instant, ou scannez depuis une photo.',
    'gate.off.title': 'L\'autorisation de la caméra est désactivée',
    'gate.off.message': 'Autorisez l\'accès à la caméra dans les réglages du navigateur, puis touchez à nouveau.',
    'gate.retry': 'Réessayer la caméra',

    'status.starting': 'Démarrage de la caméra.',
    'status.aim': 'Alignez le code sur le guide en points.',
    'status.closer': 'Rapprochez-vous pour que le code apparaisse plus grand à l\'écran.',
    'status.clipped': 'Reculez un peu — le code est coupé.',
    'status.steadyScan': 'L\'image est stable — lecture précise par rapport au guide.',
    'status.tapToStart': 'Touchez l\'écran pour démarrer la caméra.',
    'status.noHttps': 'La caméra n\'est pas disponible car la connexion n\'est pas en HTTPS.',
    'status.unsupported': 'Ce navigateur ne peut pas utiliser la caméra.',
    'status.checkingPhoto': 'Vérification de la photo.',
    'status.photoUnreadable': 'Impossible de lire cette photo. Choisissez-en une autre.',
    'status.photoNoResult': 'Aucun code trouvé dans cette photo. Choisissez-en une autre ou démarrez la caméra.',
    'status.startOrPick': 'Démarrez la caméra ou choisissez une autre photo.',
    'toast.photoNoResult': 'Aucun code trouvé dans cette photo.',
    'toast.photoUnreadable': 'Impossible de lire cette photo.',
    'status.decoded': 'Code lu.',
    'status.frameError': 'Un problème est survenu pendant le traitement de l\'image. Redémarrez.',
    'status.restart': 'Redémarrez la caméra.',
    'status.tapToContinue': 'Touchez l\'écran pour continuer à scanner.',
    'status.startOrPhoto': 'Démarrez la caméra ou scannez depuis une photo.',
    'status.hiddenStopped': 'La caméra s\'est arrêtée quand vous avez quitté l\'onglet. Redémarrez pour continuer.',
    'status.hiddenRestart': 'La caméra s\'est arrêtée quand vous avez quitté l\'onglet. Redémarrez-la.',

    'result.title': 'Résultat du scan',
    'result.close': 'Fermer le résultat du scan',
    'result.generic': 'Contenu lu',
    'result.popupBlocked': 'Votre navigateur a bloqué le nouvel onglet. Touchez le bouton ci-dessous pour l\'ouvrir.',
    'result.openLink': 'Ouvrir le lien',
    'result.rescan': 'Scanner à nouveau',
    'result.closeButton': 'Fermer',
    'result.text.title': 'Texte lu',
    'result.text.hint': 'Vous pouvez consulter ou copier le contenu.',
    'result.text.field': 'Contenu',
    'result.url.title': 'Lien lu',
    'result.url.opened': 'L\'adresse a été ouverte dans un nouvel onglet.',
    'result.url.manual': 'Touchez le bouton ci-dessous pour ouvrir l\'adresse.',
    'result.url.field': 'Adresse',
    'result.wifi.title': 'Informations Wi-Fi lues',
    'result.wifi.hint': 'Le web ne peut pas se connecter directement à un réseau Wi-Fi. Copiez les valeurs dont vous avez besoin.',
    'result.wifi.security': 'Sécurité',
    'result.wifi.password': 'Mot de passe',
    'result.card.title': 'Carte de visite lue',
    'result.card.hint': 'Les coordonnées et le site web sont prêts à l\'emploi.',
    'result.card.name': 'Nom',
    'result.card.org': 'Organisation',
    'result.card.phone': 'Téléphone',
    'result.card.email': 'E-mail',
    'result.card.site': 'Site web',
    'copy.button': 'Copier',
    'copy.suffix': ' à copier',
    'copy.done': 'Copié',
    'copy.doneSuffix': ' — copie effectuée.',
    'copy.failSuffix': ' — la copie a échoué. Sélectionnez le texte et copiez-le manuellement.',
    'value.none': 'Aucun',
    'camera.fallback': 'Caméra',

    'lab.notice.title': 'Version d\'essai',
    'lab.notice.body': 'Cette adresse est une version d\'essai. Les informations sur l\'appareil et la caméra ainsi que des images réduites (échantillon stratifié des échecs, de l\'image précédant la réussite et de la réussite) sont transmises en temps réel. Le contenu de la charge utile n\'est pas transmis. La version stable traite les images uniquement sur l\'appareil.',
    'lab.expectedArm.label': 'Bras de localisateur attendu',
    'lab.expectedArm.unknown': 'Inconnu',
    'lab.expectedArm.a': 'A (ancien)',
    'lab.expectedArm.b': 'B (nouveau)',
    'lab.expectedLayout.label': 'Disposition attendue',
    'lab.expectedLayout.unknown': 'Inconnue',
    'lab.expectedLayout.v0': 'v0',
    'lab.expectedLayout.v2r2': 'v2r2',
    'lab.expectedLayout.v1r2': 'v1r2',
    'lab.expectedLayout.v0x': 'v0X',
    'lab.expectedLayout.v0xq': 'v0XQ',
    'lab.expectedLayout.v0w': 'v0W',
    'lab.expectedLayout.v0w2': 'v0W2',
    'lab.expectedLayout.v0wq': 'v0WQ',
    'lab.expectedLayout.v0t': 'v0T',
    'lab.expectedLayout.v0ty': 'v0TY',
    'lab.expectedLayout.v0tr': 'v0TR',
    'lab.expectedLayout.v0trq': 'v0TRQ',
    'lab.expectedLayout.v0try': 'v0TRY',
    'lab.expectedFinder.label': 'Repère central attendu',
    'lab.expectedFinder.unknown': 'Inconnu',
    'lab.expectedFinder.bullseye': 'Œil-de-bœuf',
    'lab.expectedFinder.cube-bullseye': 'Œil-de-bœuf à cube',
    'lab.expectedFinder.central-cube-3tone': 'Cube 3 tons',
    'lab.expectedFinder.center-qr': 'QR',
    'lab.expectedFinder.pinwheel-3-0101-cw-missing-solid': 'pinwheel',
    'lab.expectedFinder.gap-ring-01-2-1-solid': 'gap-ring',
    'lab.expectedFinder.flower-7-0020-coprime-offset': 'flower',
    'lab.expectedFinder.swirl-2-200': 'swirl',
    'lab.expectedFinder.pinwheel-c2-2-1100-cw': 'pinwheel-c2',
    'lab.expectedFinder.gap-ring-01-2-1-open': 'gap-ring-open',
    'lab.expectedFinder.flower-7-1020-coprime-offset': 'flower-1020',
    'lab.expectedFinder.swirl-c2-5-5-11-both': 'swirl-c2',
    'lab.expectedFinder.tristar-refined-h3': 'tristar',
    'lab.expectedFinder.tree-refined-h3': 'tree',
    'lab.expectedFinder.cats-refined-h3': 'cats',
    'lab.expectedFinder.oak-nitrogen-r2': 'Nitrogen',
    'lab.expectedFinder.oak-aspirin': 'Aspirin',
    'lab.expectedFinder.oak-benzene': 'Benzene',
    'lab.expectedOuter.label': 'Repère extérieur / réservation attendu',
    'lab.expectedOuter.unknown': 'Inconnu',
    'lab.expectedOuter.none': 'Aucun',
    'lab.expectedOuter.daehan': 'sagoae',
    'lab.expectedOuter.a-cm': 'A-CM (réservation)',
    'lab.expectedOuter.o-cm': 'O-CM (réservation)',
    'lab.debug.toggle': 'Superposition de détection',
    'lab.daehan.toggle': 'taegeuk + sagoae',
    'lab.expectedTones.label': 'Tons attendus',
    'lab.expectedTones.unknown': 'Inconnus',
    'lab.expectedTones.two': '2 tons',
    'lab.expectedTones.three': '3 tons',
  },

  it: {
    'update.ready': 'È pronta una nuova versione.',
    'update.apply': 'Applica ora',
    'app.label': 'Scanner TLcube',
    'document.title': 'Scanner TLcube',
    'camera.label': 'Vista della fotocamera per scansionare un codice TLcube',
    'fps.title': 'Fotogrammi elaborati al secondo (tentativi di decodifica)',
    'brand.label': 'Sito di presentazione di TLcube (nuova finestra)',
    'guide.label': 'Guida di scansione',
    'guide.message': 'Allinea il codice TLcube alla guida a punti.',
    'guide.dots': 'Fai coincidere i vertici del codice con i punti esterni, l\'esagono della silhouette O con gli anelli intermedi e il cubo centrale con i punti interni.',
    'guide.tlcubeOnly': 'I codici QR e gli altri codici a barre non sono supportati.',
    'zoom.in': 'Ingrandisci',
    'zoom.out': 'Riduci',
    'zoom.slider': 'Livello di zoom',
    'zoom.failed': 'Non è stato possibile applicare lo zoom della fotocamera. Viene ritagliato il centro.',
    'status.preparing': 'Preparazione della fotocamera.',
    'button.photo': 'Scansiona da una foto',
    'picker.label': 'Scegli l\'obiettivo',
    'input.label': 'Scegli una foto da scansionare',
    'footer.intro': 'Informazioni',
    'footer.generator': 'Generatore',
    'lang.label': 'Lingua',

    'gate.title': 'Avviare la fotocamera?',
    'gate.message': 'Consenti l\'accesso alla fotocamera e la scansione parte subito.',
    'gate.start': 'Tocca per avviare la fotocamera',
    'gate.https.title': 'È necessaria una connessione HTTPS',
    'gate.https.message': 'La fotocamera non è disponibile su una connessione non HTTPS. È comunque possibile scansionare da una foto.',
    'gate.https.start': 'La fotocamera richiede HTTPS',
    'gate.unsupported.title': 'Fotocamera non disponibile',
    'gate.unsupported.message': 'Questo browser non supporta l\'accesso alla fotocamera. È possibile scansionare da una foto.',
    'gate.denied.title': 'Serve l\'autorizzazione alla fotocamera',
    'gate.denied.message': 'Consenti l\'accesso alla fotocamera nel browser, poi tocca di nuovo.',
    'gate.notfound.title': 'Nessuna fotocamera trovata',
    'gate.notfound.message': 'Controlla il collegamento della fotocamera e tocca di nuovo, oppure scansiona da una foto.',
    'gate.failed.title': 'Non è stato possibile aprire la fotocamera',
    'gate.failed.message': 'Riprova tra un istante, oppure scansiona da una foto.',
    'gate.off.title': 'L\'autorizzazione alla fotocamera è disattivata',
    'gate.off.message': 'Consenti l\'accesso alla fotocamera nelle impostazioni del browser, poi tocca di nuovo.',
    'gate.retry': 'Riprova con la fotocamera',

    'status.starting': 'Avvio della fotocamera.',
    'status.aim': 'Allinea il codice alla guida a punti.',
    'status.closer': 'Avvicinati perché il codice appaia più grande sullo schermo.',
    'status.clipped': 'Allontanati un po\' — il codice viene tagliato.',
    'status.steadyScan': 'L\'inquadratura è stabile — lettura precisa rispetto alla guida.',
    'status.tapToStart': 'Tocca lo schermo per avviare la fotocamera.',
    'status.noHttps': 'La fotocamera non è disponibile perché la connessione non è HTTPS.',
    'status.unsupported': 'Questo browser non può usare la fotocamera.',
    'status.checkingPhoto': 'Controllo della foto.',
    'status.photoUnreadable': 'Non è stato possibile leggere questa foto. Scegline un\'altra.',
    'status.photoNoResult': 'Nessun codice trovato in questa foto. Scegline un\'altra o avvia la fotocamera.',
    'status.startOrPick': 'Avvia la fotocamera o scegli un\'altra foto.',
    'toast.photoNoResult': 'Nessun codice trovato in questa foto.',
    'toast.photoUnreadable': 'Non è stato possibile leggere questa foto.',
    'status.decoded': 'Codice letto.',
    'status.frameError': 'Si è verificato un problema durante l\'elaborazione del fotogramma. Riavvia.',
    'status.restart': 'Riavvia la fotocamera.',
    'status.tapToContinue': 'Tocca lo schermo per continuare a scansionare.',
    'status.startOrPhoto': 'Avvia la fotocamera o scansiona da una foto.',
    'status.hiddenStopped': 'La fotocamera si è fermata quando hai lasciato la scheda. Riavvia per continuare.',
    'status.hiddenRestart': 'La fotocamera si è fermata quando hai lasciato la scheda. Riavviala.',

    'result.title': 'Risultato della scansione',
    'result.close': 'Chiudi il risultato della scansione',
    'result.generic': 'Contenuto letto',
    'result.popupBlocked': 'Il browser ha bloccato la nuova scheda. Tocca il pulsante qui sotto per aprirla.',
    'result.openLink': 'Apri il link',
    'result.rescan': 'Scansiona di nuovo',
    'result.closeButton': 'Chiudi',
    'result.text.title': 'Testo letto',
    'result.text.hint': 'È possibile consultare o copiare il contenuto.',
    'result.text.field': 'Contenuto',
    'result.url.title': 'Link letto',
    'result.url.opened': 'L\'indirizzo è stato aperto in una nuova scheda.',
    'result.url.manual': 'Tocca il pulsante qui sotto per aprire l\'indirizzo.',
    'result.url.field': 'Indirizzo',
    'result.wifi.title': 'Dati Wi-Fi letti',
    'result.wifi.hint': 'Dal web non è possibile connettersi direttamente a una rete Wi-Fi. Copia i valori che ti servono.',
    'result.wifi.security': 'Sicurezza',
    'result.wifi.password': 'Password',
    'result.card.title': 'Biglietto da visita letto',
    'result.card.hint': 'I contatti e il sito web sono pronti all\'uso.',
    'result.card.name': 'Nome',
    'result.card.org': 'Organizzazione',
    'result.card.phone': 'Telefono',
    'result.card.email': 'E-mail',
    'result.card.site': 'Sito web',
    'copy.button': 'Copia',
    'copy.suffix': ' da copiare',
    'copy.done': 'Copiato',
    'copy.doneSuffix': ' — copia eseguita.',
    'copy.failSuffix': ' — copia non riuscita. Seleziona il testo e copialo manualmente.',
    'value.none': 'Nessuno',
    'camera.fallback': 'Fotocamera',

    'lab.notice.title': 'Versione di prova',
    'lab.notice.body': 'Questo indirizzo è una versione di prova. Le informazioni su dispositivo e fotocamera e le immagini ridotte dei fotogrammi (campione stratificato di fallimenti, del fotogramma precedente al successo e del successo) vengono inviate in tempo reale. Il contenuto del payload non viene inviato. La versione stabile elabora i fotogrammi solo sul dispositivo.',
    'lab.expectedArm.label': 'Braccio del localizzatore atteso',
    'lab.expectedArm.unknown': 'Sconosciuto',
    'lab.expectedArm.a': 'A (vecchio)',
    'lab.expectedArm.b': 'B (nuovo)',
    'lab.expectedLayout.label': 'Layout atteso',
    'lab.expectedLayout.unknown': 'Sconosciuto',
    'lab.expectedLayout.v0': 'v0',
    'lab.expectedLayout.v2r2': 'v2r2',
    'lab.expectedLayout.v1r2': 'v1r2',
    'lab.expectedLayout.v0x': 'v0X',
    'lab.expectedLayout.v0xq': 'v0XQ',
    'lab.expectedLayout.v0w': 'v0W',
    'lab.expectedLayout.v0w2': 'v0W2',
    'lab.expectedLayout.v0wq': 'v0WQ',
    'lab.expectedLayout.v0t': 'v0T',
    'lab.expectedLayout.v0ty': 'v0TY',
    'lab.expectedLayout.v0tr': 'v0TR',
    'lab.expectedLayout.v0trq': 'v0TRQ',
    'lab.expectedLayout.v0try': 'v0TRY',
    'lab.expectedFinder.label': 'Mirino centrale atteso',
    'lab.expectedFinder.unknown': 'Sconosciuto',
    'lab.expectedFinder.bullseye': 'Bullseye',
    'lab.expectedFinder.cube-bullseye': 'Bullseye con cubo',
    'lab.expectedFinder.central-cube-3tone': 'Cubo a 3 toni',
    'lab.expectedFinder.center-qr': 'QR',
    'lab.expectedFinder.pinwheel-3-0101-cw-missing-solid': 'pinwheel',
    'lab.expectedFinder.gap-ring-01-2-1-solid': 'gap-ring',
    'lab.expectedFinder.flower-7-0020-coprime-offset': 'flower',
    'lab.expectedFinder.swirl-2-200': 'swirl',
    'lab.expectedFinder.pinwheel-c2-2-1100-cw': 'pinwheel-c2',
    'lab.expectedFinder.gap-ring-01-2-1-open': 'gap-ring-open',
    'lab.expectedFinder.flower-7-1020-coprime-offset': 'flower-1020',
    'lab.expectedFinder.swirl-c2-5-5-11-both': 'swirl-c2',
    'lab.expectedFinder.tristar-refined-h3': 'tristar',
    'lab.expectedFinder.tree-refined-h3': 'tree',
    'lab.expectedFinder.cats-refined-h3': 'cats',
    'lab.expectedFinder.oak-nitrogen-r2': 'Nitrogen',
    'lab.expectedFinder.oak-aspirin': 'Aspirin',
    'lab.expectedFinder.oak-benzene': 'Benzene',
    'lab.expectedOuter.label': 'Mirino esterno / prenotazione atteso',
    'lab.expectedOuter.unknown': 'Sconosciuto',
    'lab.expectedOuter.none': 'Nessuno',
    'lab.expectedOuter.daehan': 'sagoae',
    'lab.expectedOuter.a-cm': 'A-CM (prenotazione)',
    'lab.expectedOuter.o-cm': 'O-CM (prenotazione)',
    'lab.debug.toggle': 'Overlay di rilevamento',
    'lab.daehan.toggle': 'taegeuk + sagoae',
    'lab.expectedTones.label': 'Toni attesi',
    'lab.expectedTones.unknown': 'Sconosciuti',
    'lab.expectedTones.two': '2 toni',
    'lab.expectedTones.three': '3 toni',
  },

  de: {
    'update.ready': 'Eine neue Version steht bereit.',
    'update.apply': 'Jetzt anwenden',
    'app.label': 'TLcube-Scanner',
    'document.title': 'TLcube-Scanner',
    'camera.label': 'Kameraansicht zum Scannen eines TLcube-Codes',
    'fps.title': 'Verarbeitete Bilder pro Sekunde (Dekodierversuche)',
    'brand.label': 'TLcube-Übersichtsseite (neues Fenster)',
    'guide.label': 'Scanhilfe',
    'guide.message': 'Richten Sie den TLcube-Code an der Punkthilfe aus.',
    'guide.dots': 'Legen Sie die Ecken des Codes auf die äußeren Punkte, das Sechseck der O-Silhouette auf die mittleren Ringe und den zentralen Würfel auf die inneren Punkte.',
    'guide.tlcubeOnly': 'QR-Codes und andere Barcodes werden nicht gelesen.',
    'zoom.in': 'Vergrößern',
    'zoom.out': 'Verkleinern',
    'zoom.slider': 'Zoomstufe',
    'zoom.failed': 'Der Kamerazoom konnte nicht angewendet werden. Stattdessen wird die Bildmitte zugeschnitten.',
    'status.preparing': 'Die Kamera wird vorbereitet.',
    'button.photo': 'Aus einem Foto scannen',
    'picker.label': 'Kameraobjektiv wählen',
    'input.label': 'Foto zum Scannen wählen',
    'footer.intro': 'Info',
    'footer.generator': 'Generator',
    'lang.label': 'Sprache',

    'gate.title': 'Kamera starten?',
    'gate.message': 'Erlauben Sie den Kamerazugriff, dann startet der Scan sofort.',
    'gate.start': 'Zum Starten der Kamera tippen',
    'gate.https.title': 'HTTPS ist erforderlich',
    'gate.https.message': 'Über eine Verbindung ohne HTTPS ist die Kamera nicht verfügbar. Sie können weiterhin aus einem Foto scannen.',
    'gate.https.start': 'Kamera benötigt HTTPS',
    'gate.unsupported.title': 'Kamera nicht verfügbar',
    'gate.unsupported.message': 'Dieser Browser unterstützt den Kamerazugriff nicht. Sie können aus einem Foto scannen.',
    'gate.denied.title': 'Kameraberechtigung erforderlich',
    'gate.denied.message': 'Erlauben Sie den Kamerazugriff im Browser und tippen Sie erneut.',
    'gate.notfound.title': 'Keine Kamera gefunden',
    'gate.notfound.message': 'Prüfen Sie die Kameraverbindung und tippen Sie erneut, oder scannen Sie aus einem Foto.',
    'gate.failed.title': 'Die Kamera konnte nicht geöffnet werden',
    'gate.failed.message': 'Tippen Sie gleich erneut, oder scannen Sie aus einem Foto.',
    'gate.off.title': 'Die Kameraberechtigung ist deaktiviert',
    'gate.off.message': 'Erlauben Sie den Kamerazugriff in den Browsereinstellungen und tippen Sie erneut.',
    'gate.retry': 'Kamera erneut versuchen',

    'status.starting': 'Die Kamera wird gestartet.',
    'status.aim': 'Richten Sie den Code an der Punkthilfe aus.',
    'status.closer': 'Gehen Sie näher heran, damit der Code größer im Bild erscheint.',
    'status.clipped': 'Gehen Sie etwas zurück — der Code wird abgeschnitten.',
    'status.steadyScan': 'Das Bild steht still — es wird präzise anhand der Hilfe gelesen.',
    'status.tapToStart': 'Tippen Sie auf den Bildschirm, um die Kamera zu starten.',
    'status.noHttps': 'Die Kamera ist nicht verfügbar, weil dies keine HTTPS-Verbindung ist.',
    'status.unsupported': 'Dieser Browser kann die Kamera nicht verwenden.',
    'status.checkingPhoto': 'Das Foto wird geprüft.',
    'status.photoUnreadable': 'Dieses Foto konnte nicht gelesen werden. Bitte wählen Sie ein anderes.',
    'status.photoNoResult': 'In diesem Foto wurde kein Code gefunden. Wählen Sie ein anderes oder starten Sie die Kamera.',
    'status.startOrPick': 'Starten Sie die Kamera oder wählen Sie ein anderes Foto.',
    'toast.photoNoResult': 'In diesem Foto wurde kein Code gefunden.',
    'toast.photoUnreadable': 'Dieses Foto konnte nicht gelesen werden.',
    'status.decoded': 'Code gelesen.',
    'status.frameError': 'Bei der Verarbeitung des Bildes ist ein Problem aufgetreten. Bitte starten Sie neu.',
    'status.restart': 'Bitte starten Sie die Kamera erneut.',
    'status.tapToContinue': 'Tippen Sie auf den Bildschirm, um weiter zu scannen.',
    'status.startOrPhoto': 'Starten Sie die Kamera oder scannen Sie aus einem Foto.',
    'status.hiddenStopped': 'Die Kamera wurde beim Verlassen des Tabs gestoppt. Starten Sie neu, um fortzufahren.',
    'status.hiddenRestart': 'Die Kamera wurde beim Verlassen des Tabs gestoppt. Bitte starten Sie sie erneut.',

    'result.title': 'Scan-Ergebnis',
    'result.close': 'Scan-Ergebnis schließen',
    'result.generic': 'Inhalt gelesen',
    'result.popupBlocked': 'Ihr Browser hat den neuen Tab blockiert. Tippen Sie unten auf die Schaltfläche, um ihn zu öffnen.',
    'result.openLink': 'Link öffnen',
    'result.rescan': 'Erneut scannen',
    'result.closeButton': 'Schließen',
    'result.text.title': 'Text gelesen',
    'result.text.hint': 'Sie können den Inhalt ansehen oder kopieren.',
    'result.text.field': 'Inhalt',
    'result.url.title': 'Link gelesen',
    'result.url.opened': 'Die Adresse wurde in einem neuen Tab geöffnet.',
    'result.url.manual': 'Tippen Sie unten auf die Schaltfläche, um die Adresse zu öffnen.',
    'result.url.field': 'Adresse',
    'result.wifi.title': 'WLAN-Daten gelesen',
    'result.wifi.hint': 'Im Web lässt sich ein WLAN nicht direkt verbinden. Kopieren Sie die benötigten Werte.',
    'result.wifi.security': 'Sicherheit',
    'result.wifi.password': 'Passwort',
    'result.card.title': 'Visitenkarte gelesen',
    'result.card.hint': 'Kontaktdaten und Website sind sofort nutzbar.',
    'result.card.name': 'Name',
    'result.card.org': 'Organisation',
    'result.card.phone': 'Telefon',
    'result.card.email': 'E-Mail',
    'result.card.site': 'Website',
    'copy.button': 'Kopieren',
    'copy.suffix': ' kopieren',
    'copy.done': 'Kopiert',
    'copy.doneSuffix': ' wurde kopiert.',
    'copy.failSuffix': ' konnte nicht kopiert werden. Bitte markieren Sie den Text und kopieren Sie ihn manuell.',
    'value.none': 'Keine',
    'camera.fallback': 'Kamera',

    'lab.notice.title': 'Testversion',
    'lab.notice.body': 'Diese Adresse ist eine Testversion. Geräte- und Kameradaten sowie verkleinerte Bilder (geschichtete Stichprobe aus Fehlschlägen, dem Bild vor dem Erfolg und dem Erfolg) werden in Echtzeit übertragen. Der Inhalt der Nutzdaten wird nicht übertragen. Die stabile Version verarbeitet Bilder nur auf dem Gerät.',
    'lab.expectedArm.label': 'Erwarteter Lokator-Arm',
    'lab.expectedArm.unknown': 'Unbekannt',
    'lab.expectedArm.a': 'A (alt)',
    'lab.expectedArm.b': 'B (neu)',
    'lab.expectedLayout.label': 'Erwartetes Layout',
    'lab.expectedLayout.unknown': 'Unbekannt',
    'lab.expectedLayout.v0': 'v0',
    'lab.expectedLayout.v2r2': 'v2r2',
    'lab.expectedLayout.v1r2': 'v1r2',
    'lab.expectedLayout.v0x': 'v0X',
    'lab.expectedLayout.v0xq': 'v0XQ',
    'lab.expectedLayout.v0w': 'v0W',
    'lab.expectedLayout.v0w2': 'v0W2',
    'lab.expectedLayout.v0wq': 'v0WQ',
    'lab.expectedLayout.v0t': 'v0T',
    'lab.expectedLayout.v0ty': 'v0TY',
    'lab.expectedLayout.v0tr': 'v0TR',
    'lab.expectedLayout.v0trq': 'v0TRQ',
    'lab.expectedLayout.v0try': 'v0TRY',
    'lab.expectedFinder.label': 'Erwarteter zentraler Finder',
    'lab.expectedFinder.unknown': 'Unbekannt',
    'lab.expectedFinder.bullseye': 'Bullseye',
    'lab.expectedFinder.cube-bullseye': 'Bullseye mit Würfel',
    'lab.expectedFinder.central-cube-3tone': '3-Ton-Würfel',
    'lab.expectedFinder.center-qr': 'QR',
    'lab.expectedFinder.pinwheel-3-0101-cw-missing-solid': 'pinwheel',
    'lab.expectedFinder.gap-ring-01-2-1-solid': 'gap-ring',
    'lab.expectedFinder.flower-7-0020-coprime-offset': 'flower',
    'lab.expectedFinder.swirl-2-200': 'swirl',
    'lab.expectedFinder.pinwheel-c2-2-1100-cw': 'pinwheel-c2',
    'lab.expectedFinder.gap-ring-01-2-1-open': 'gap-ring-open',
    'lab.expectedFinder.flower-7-1020-coprime-offset': 'flower-1020',
    'lab.expectedFinder.swirl-c2-5-5-11-both': 'swirl-c2',
    'lab.expectedFinder.tristar-refined-h3': 'tristar',
    'lab.expectedFinder.tree-refined-h3': 'tree',
    'lab.expectedFinder.cats-refined-h3': 'cats',
    'lab.expectedFinder.oak-nitrogen-r2': 'Nitrogen',
    'lab.expectedFinder.oak-aspirin': 'Aspirin',
    'lab.expectedFinder.oak-benzene': 'Benzene',
    'lab.expectedOuter.label': 'Erwarteter äußerer Finder / Platzreservierung',
    'lab.expectedOuter.unknown': 'Unbekannt',
    'lab.expectedOuter.none': 'Keiner',
    'lab.expectedOuter.daehan': 'sagoae',
    'lab.expectedOuter.a-cm': 'A-CM (Platz)',
    'lab.expectedOuter.o-cm': 'O-CM (Platz)',
    'lab.debug.toggle': 'Erkennungs-Overlay',
    'lab.daehan.toggle': 'taegeuk + sagoae',
    'lab.expectedTones.label': 'Erwartete Tonwerte',
    'lab.expectedTones.unknown': 'Unbekannt',
    'lab.expectedTones.two': '2 Tonwerte',
    'lab.expectedTones.three': '3 Tonwerte',
  },

  es: {
    'update.ready': 'Hay una nueva versión lista.',
    'update.apply': 'Aplicar ahora',
    'app.label': 'Escáner TLcube',
    'document.title': 'Escáner TLcube',
    'camera.label': 'Vista de la cámara para escanear un código TLcube',
    'fps.title': 'Fotogramas procesados por segundo (intentos de descodificación)',
    'brand.label': 'Sitio de presentación de TLcube (ventana nueva)',
    'guide.label': 'Guía de escaneo',
    'guide.message': 'Alinee el código TLcube con la guía de puntos.',
    'guide.dots': 'Haga coincidir las esquinas del código con los puntos exteriores, el hexágono de la silueta O con los anillos intermedios y el cubo central con los puntos interiores.',
    'guide.tlcubeOnly': 'Los códigos QR y otros códigos de barras no son compatibles.',
    'zoom.in': 'Acercar',
    'zoom.out': 'Alejar',
    'zoom.slider': 'Nivel de zoom',
    'zoom.failed': 'No se ha podido aplicar el zoom de la cámara. Se recorta el centro en su lugar.',
    'status.preparing': 'Preparando la cámara.',
    'button.photo': 'Escanear desde una foto',
    'picker.label': 'Elegir el objetivo',
    'input.label': 'Elegir una foto para escanear',
    'footer.intro': 'Acerca de',
    'footer.generator': 'Generador',
    'lang.label': 'Idioma',

    'gate.title': '¿Iniciar la cámara?',
    'gate.message': 'Permita el acceso a la cámara y el escaneo empezará enseguida.',
    'gate.start': 'Toque para iniciar la cámara',
    'gate.https.title': 'Se requiere HTTPS',
    'gate.https.message': 'La cámara no está disponible en una conexión que no sea HTTPS. Aun así puede escanear desde una foto.',
    'gate.https.start': 'La cámara necesita HTTPS',
    'gate.unsupported.title': 'Cámara no disponible',
    'gate.unsupported.message': 'Este navegador no admite el acceso a la cámara. Puede escanear desde una foto.',
    'gate.denied.title': 'Se necesita permiso de cámara',
    'gate.denied.message': 'Permita el acceso a la cámara en el navegador y vuelva a tocar.',
    'gate.notfound.title': 'No se ha encontrado ninguna cámara',
    'gate.notfound.message': 'Compruebe la conexión de la cámara y vuelva a tocar, o escanee desde una foto.',
    'gate.failed.title': 'No se ha podido abrir la cámara',
    'gate.failed.message': 'Vuelva a tocar en un momento, o escanee desde una foto.',
    'gate.off.title': 'El permiso de cámara está desactivado',
    'gate.off.message': 'Permita el acceso a la cámara en los ajustes del navegador y vuelva a tocar.',
    'gate.retry': 'Reintentar la cámara',

    'status.starting': 'Iniciando la cámara.',
    'status.aim': 'Alinee el código con la guía de puntos.',
    'status.closer': 'Acérquese para que el código se vea más grande en pantalla.',
    'status.clipped': 'Aléjese un poco — el código se está cortando.',
    'status.steadyScan': 'La imagen está estable — lectura precisa respecto a la guía.',
    'status.tapToStart': 'Toque la pantalla para iniciar la cámara.',
    'status.noHttps': 'La cámara no está disponible porque esta conexión no es HTTPS.',
    'status.unsupported': 'Este navegador no puede usar la cámara.',
    'status.checkingPhoto': 'Comprobando la foto.',
    'status.photoUnreadable': 'No se ha podido leer esa foto. Elija otra.',
    'status.photoNoResult': 'No se ha encontrado ningún código en esa foto. Elija otra o inicie la cámara.',
    'status.startOrPick': 'Inicie la cámara o elija otra foto.',
    'toast.photoNoResult': 'No se ha encontrado ningún código en esa foto.',
    'toast.photoUnreadable': 'No se ha podido leer esa foto.',
    'status.decoded': 'Código leído.',
    'status.frameError': 'Ha ocurrido un problema al procesar el fotograma. Vuelva a iniciar.',
    'status.restart': 'Vuelva a iniciar la cámara.',
    'status.tapToContinue': 'Toque la pantalla para seguir escaneando.',
    'status.startOrPhoto': 'Inicie la cámara o escanee desde una foto.',
    'status.hiddenStopped': 'La cámara se detuvo al salir de la pestaña. Vuelva a iniciarla para continuar.',
    'status.hiddenRestart': 'La cámara se detuvo al salir de la pestaña. Vuelva a iniciarla.',

    'result.title': 'Resultado del escaneo',
    'result.close': 'Cerrar el resultado del escaneo',
    'result.generic': 'Contenido leído',
    'result.popupBlocked': 'El navegador ha bloqueado la pestaña nueva. Toque el botón de abajo para abrirla.',
    'result.openLink': 'Abrir el enlace',
    'result.rescan': 'Escanear de nuevo',
    'result.closeButton': 'Cerrar',
    'result.text.title': 'Texto leído',
    'result.text.hint': 'Puede revisar o copiar el contenido.',
    'result.text.field': 'Contenido',
    'result.url.title': 'Enlace leído',
    'result.url.opened': 'Se ha abierto la dirección en una pestaña nueva.',
    'result.url.manual': 'Toque el botón de abajo para abrir la dirección.',
    'result.url.field': 'Dirección',
    'result.wifi.title': 'Datos de Wi-Fi leídos',
    'result.wifi.hint': 'Desde la web no se puede conectar directamente a una red Wi-Fi. Copie los valores que necesite.',
    'result.wifi.security': 'Seguridad',
    'result.wifi.password': 'Contraseña',
    'result.card.title': 'Tarjeta de contacto leída',
    'result.card.hint': 'Los datos de contacto y el sitio web están listos para usar.',
    'result.card.name': 'Nombre',
    'result.card.org': 'Organización',
    'result.card.phone': 'Teléfono',
    'result.card.email': 'Correo electrónico',
    'result.card.site': 'Sitio web',
    'copy.button': 'Copiar',
    'copy.suffix': ' para copiar',
    'copy.done': 'Copiado',
    'copy.doneSuffix': ' — copia realizada.',
    'copy.failSuffix': ' — no se ha podido copiar. Seleccione el texto y cópielo manualmente.',
    'value.none': 'Ninguno',
    'camera.fallback': 'Cámara',

    'lab.notice.title': 'Versión de prueba',
    'lab.notice.body': 'Esta dirección es una versión de prueba. Los datos del dispositivo y de la cámara y las imágenes reducidas de los fotogramas (muestra estratificada de fallos, del fotograma previo al acierto y del acierto) se envían en tiempo real. El contenido de la carga útil no se envía. La versión estable procesa los fotogramas solo en el dispositivo.',
    'lab.expectedArm.label': 'Brazo del localizador esperado',
    'lab.expectedArm.unknown': 'Desconocido',
    'lab.expectedArm.a': 'A (antiguo)',
    'lab.expectedArm.b': 'B (nuevo)',
    'lab.expectedLayout.label': 'Disposición esperada',
    'lab.expectedLayout.unknown': 'Desconocida',
    'lab.expectedLayout.v0': 'v0',
    'lab.expectedLayout.v2r2': 'v2r2',
    'lab.expectedLayout.v1r2': 'v1r2',
    'lab.expectedLayout.v0x': 'v0X',
    'lab.expectedLayout.v0xq': 'v0XQ',
    'lab.expectedLayout.v0w': 'v0W',
    'lab.expectedLayout.v0w2': 'v0W2',
    'lab.expectedLayout.v0wq': 'v0WQ',
    'lab.expectedLayout.v0t': 'v0T',
    'lab.expectedLayout.v0ty': 'v0TY',
    'lab.expectedLayout.v0tr': 'v0TR',
    'lab.expectedLayout.v0trq': 'v0TRQ',
    'lab.expectedLayout.v0try': 'v0TRY',
    'lab.expectedFinder.label': 'Localizador central esperado',
    'lab.expectedFinder.unknown': 'Desconocido',
    'lab.expectedFinder.bullseye': 'Diana',
    'lab.expectedFinder.cube-bullseye': 'Diana con cubo',
    'lab.expectedFinder.central-cube-3tone': 'Cubo de 3 tonos',
    'lab.expectedFinder.center-qr': 'QR',
    'lab.expectedFinder.pinwheel-3-0101-cw-missing-solid': 'pinwheel',
    'lab.expectedFinder.gap-ring-01-2-1-solid': 'gap-ring',
    'lab.expectedFinder.flower-7-0020-coprime-offset': 'flower',
    'lab.expectedFinder.swirl-2-200': 'swirl',
    'lab.expectedFinder.pinwheel-c2-2-1100-cw': 'pinwheel-c2',
    'lab.expectedFinder.gap-ring-01-2-1-open': 'gap-ring-open',
    'lab.expectedFinder.flower-7-1020-coprime-offset': 'flower-1020',
    'lab.expectedFinder.swirl-c2-5-5-11-both': 'swirl-c2',
    'lab.expectedFinder.tristar-refined-h3': 'tristar',
    'lab.expectedFinder.tree-refined-h3': 'tree',
    'lab.expectedFinder.cats-refined-h3': 'cats',
    'lab.expectedFinder.oak-nitrogen-r2': 'Nitrogen',
    'lab.expectedFinder.oak-aspirin': 'Aspirin',
    'lab.expectedFinder.oak-benzene': 'Benzene',
    'lab.expectedOuter.label': 'Localizador exterior / reserva esperado',
    'lab.expectedOuter.unknown': 'Desconocido',
    'lab.expectedOuter.none': 'Ninguno',
    'lab.expectedOuter.daehan': 'sagoae',
    'lab.expectedOuter.a-cm': 'A-CM (reserva)',
    'lab.expectedOuter.o-cm': 'O-CM (reserva)',
    'lab.debug.toggle': 'Superposición de detección',
    'lab.daehan.toggle': 'taegeuk + sagoae',
    'lab.expectedTones.label': 'Tonos esperados',
    'lab.expectedTones.unknown': 'Desconocidos',
    'lab.expectedTones.two': '2 tonos',
    'lab.expectedTones.three': '3 tonos',
  },

  pt: {
    'update.ready': 'Está pronta uma nova versão.',
    'update.apply': 'Aplicar agora',
    'app.label': 'Scanner TLcube',
    'document.title': 'Scanner TLcube',
    'camera.label': 'Vista da câmara para ler um código TLcube',
    'fps.title': 'Fotogramas processados por segundo (tentativas de descodificação)',
    'brand.label': 'Site de apresentação do TLcube (nova janela)',
    'guide.label': 'Guia de leitura',
    'guide.message': 'Alinhe o código TLcube pelo guia de pontos.',
    'guide.dots': 'Faça coincidir os vértices do código com os pontos exteriores, o hexágono da silhueta O com os anéis intermédios e o cubo central com os pontos interiores.',
    'guide.tlcubeOnly': 'Os códigos QR e outros códigos de barras não são suportados.',
    'zoom.in': 'Ampliar',
    'zoom.out': 'Reduzir',
    'zoom.slider': 'Nível de zoom',
    'zoom.failed': 'Não foi possível aplicar o zoom da câmara. Em alternativa, recorta-se o centro.',
    'status.preparing': 'A preparar a câmara.',
    'button.photo': 'Ler a partir de uma foto',
    'picker.label': 'Escolher a objetiva',
    'input.label': 'Escolher uma foto para ler',
    'footer.intro': 'Sobre',
    'footer.generator': 'Gerador',
    'lang.label': 'Idioma',

    'gate.title': 'Iniciar a câmara?',
    'gate.message': 'Permita o acesso à câmara e a leitura começa de imediato.',
    'gate.start': 'Toque para iniciar a câmara',
    'gate.https.title': 'É necessária uma ligação HTTPS',
    'gate.https.message': 'A câmara não está disponível numa ligação sem HTTPS. Ainda assim, pode ler a partir de uma foto.',
    'gate.https.start': 'A câmara exige HTTPS',
    'gate.unsupported.title': 'Câmara indisponível',
    'gate.unsupported.message': 'Este navegador não suporta o acesso à câmara. Pode ler a partir de uma foto.',
    'gate.denied.title': 'É necessária permissão da câmara',
    'gate.denied.message': 'Permita o acesso à câmara no navegador e toque novamente.',
    'gate.notfound.title': 'Não foi encontrada nenhuma câmara',
    'gate.notfound.message': 'Verifique a ligação da câmara e toque novamente, ou leia a partir de uma foto.',
    'gate.failed.title': 'Não foi possível abrir a câmara',
    'gate.failed.message': 'Toque novamente dentro de momentos, ou leia a partir de uma foto.',
    'gate.off.title': 'A permissão da câmara está desativada',
    'gate.off.message': 'Permita o acesso à câmara nas definições do navegador e toque novamente.',
    'gate.retry': 'Tentar a câmara novamente',

    'status.starting': 'A iniciar a câmara.',
    'status.aim': 'Alinhe o código pelo guia de pontos.',
    'status.closer': 'Aproxime-se para que o código apareça maior no ecrã.',
    'status.clipped': 'Afaste-se um pouco — o código está a ser cortado.',
    'status.steadyScan': 'A imagem está estável — leitura precisa em relação ao guia.',
    'status.tapToStart': 'Toque no ecrã para iniciar a câmara.',
    'status.noHttps': 'A câmara não está disponível porque esta ligação não é HTTPS.',
    'status.unsupported': 'Este navegador não consegue utilizar a câmara.',
    'status.checkingPhoto': 'A verificar a foto.',
    'status.photoUnreadable': 'Não foi possível ler essa foto. Escolha outra.',
    'status.photoNoResult': 'Não foi encontrado nenhum código nessa foto. Escolha outra ou inicie a câmara.',
    'status.startOrPick': 'Inicie a câmara ou escolha outra foto.',
    'toast.photoNoResult': 'Não foi encontrado nenhum código nessa foto.',
    'toast.photoUnreadable': 'Não foi possível ler essa foto.',
    'status.decoded': 'Código lido.',
    'status.frameError': 'Ocorreu um problema ao processar o fotograma. Volte a iniciar.',
    'status.restart': 'Volte a iniciar a câmara.',
    'status.tapToContinue': 'Toque no ecrã para continuar a ler.',
    'status.startOrPhoto': 'Inicie a câmara ou leia a partir de uma foto.',
    'status.hiddenStopped': 'A câmara parou quando saiu do separador. Volte a iniciar para continuar.',
    'status.hiddenRestart': 'A câmara parou quando saiu do separador. Volte a iniciá-la.',

    'result.title': 'Resultado da leitura',
    'result.close': 'Fechar o resultado da leitura',
    'result.generic': 'Conteúdo lido',
    'result.popupBlocked': 'O navegador bloqueou o novo separador. Toque no botão abaixo para o abrir.',
    'result.openLink': 'Abrir a ligação',
    'result.rescan': 'Ler novamente',
    'result.closeButton': 'Fechar',
    'result.text.title': 'Texto lido',
    'result.text.hint': 'Pode consultar ou copiar o conteúdo.',
    'result.text.field': 'Conteúdo',
    'result.url.title': 'Ligação lida',
    'result.url.opened': 'O endereço foi aberto num novo separador.',
    'result.url.manual': 'Toque no botão abaixo para abrir o endereço.',
    'result.url.field': 'Endereço',
    'result.wifi.title': 'Dados de Wi-Fi lidos',
    'result.wifi.hint': 'Na web não é possível ligar-se diretamente a uma rede Wi-Fi. Copie os valores de que precisa.',
    'result.wifi.security': 'Segurança',
    'result.wifi.password': 'Palavra-passe',
    'result.card.title': 'Cartão de visita lido',
    'result.card.hint': 'Os contactos e o site estão prontos a usar.',
    'result.card.name': 'Nome',
    'result.card.org': 'Organização',
    'result.card.phone': 'Telefone',
    'result.card.email': 'E-mail',
    'result.card.site': 'Site',
    'copy.button': 'Copiar',
    'copy.suffix': ' para copiar',
    'copy.done': 'Copiado',
    'copy.doneSuffix': ' — cópia efetuada.',
    'copy.failSuffix': ' — não foi possível copiar. Selecione o texto e copie-o manualmente.',
    'value.none': 'Nenhum',
    'camera.fallback': 'Câmara',

    'lab.notice.title': 'Versão de ensaio',
    'lab.notice.body': 'Este endereço é uma versão de ensaio. Os dados do dispositivo e da câmara e as imagens reduzidas dos fotogramas (amostra estratificada de falhas, do fotograma anterior ao êxito e do êxito) são enviados em tempo real. O conteúdo da carga útil não é enviado. A versão estável processa os fotogramas apenas no dispositivo.',
    'lab.expectedArm.label': 'Braço do localizador esperado',
    'lab.expectedArm.unknown': 'Desconhecido',
    'lab.expectedArm.a': 'A (antigo)',
    'lab.expectedArm.b': 'B (novo)',
    'lab.expectedLayout.label': 'Esquema esperado',
    'lab.expectedLayout.unknown': 'Desconhecido',
    'lab.expectedLayout.v0': 'v0',
    'lab.expectedLayout.v2r2': 'v2r2',
    'lab.expectedLayout.v1r2': 'v1r2',
    'lab.expectedLayout.v0x': 'v0X',
    'lab.expectedLayout.v0xq': 'v0XQ',
    'lab.expectedLayout.v0w': 'v0W',
    'lab.expectedLayout.v0w2': 'v0W2',
    'lab.expectedLayout.v0wq': 'v0WQ',
    'lab.expectedLayout.v0t': 'v0T',
    'lab.expectedLayout.v0ty': 'v0TY',
    'lab.expectedLayout.v0tr': 'v0TR',
    'lab.expectedLayout.v0trq': 'v0TRQ',
    'lab.expectedLayout.v0try': 'v0TRY',
    'lab.expectedFinder.label': 'Localizador central esperado',
    'lab.expectedFinder.unknown': 'Desconhecido',
    'lab.expectedFinder.bullseye': 'Alvo',
    'lab.expectedFinder.cube-bullseye': 'Alvo com cubo',
    'lab.expectedFinder.central-cube-3tone': 'Cubo de 3 tons',
    'lab.expectedFinder.center-qr': 'QR',
    'lab.expectedFinder.pinwheel-3-0101-cw-missing-solid': 'pinwheel',
    'lab.expectedFinder.gap-ring-01-2-1-solid': 'gap-ring',
    'lab.expectedFinder.flower-7-0020-coprime-offset': 'flower',
    'lab.expectedFinder.swirl-2-200': 'swirl',
    'lab.expectedFinder.pinwheel-c2-2-1100-cw': 'pinwheel-c2',
    'lab.expectedFinder.gap-ring-01-2-1-open': 'gap-ring-open',
    'lab.expectedFinder.flower-7-1020-coprime-offset': 'flower-1020',
    'lab.expectedFinder.swirl-c2-5-5-11-both': 'swirl-c2',
    'lab.expectedFinder.tristar-refined-h3': 'tristar',
    'lab.expectedFinder.tree-refined-h3': 'tree',
    'lab.expectedFinder.cats-refined-h3': 'cats',
    'lab.expectedFinder.oak-nitrogen-r2': 'Nitrogen',
    'lab.expectedFinder.oak-aspirin': 'Aspirin',
    'lab.expectedFinder.oak-benzene': 'Benzene',
    'lab.expectedOuter.label': 'Localizador externo / reserva esperado',
    'lab.expectedOuter.unknown': 'Desconhecido',
    'lab.expectedOuter.none': 'Nenhum',
    'lab.expectedOuter.daehan': 'sagoae',
    'lab.expectedOuter.a-cm': 'A-CM (reserva)',
    'lab.expectedOuter.o-cm': 'O-CM (reserva)',
    'lab.debug.toggle': 'Sobreposição de deteção',
    'lab.daehan.toggle': 'taegeuk + sagoae',
    'lab.expectedTones.label': 'Tons esperados',
    'lab.expectedTones.unknown': 'Desconhecidos',
    'lab.expectedTones.two': '2 tons',
    'lab.expectedTones.three': '3 tons',
  },
};
