/**
 * content.mjs — 소개 허브(tl.estre.so)의 **언어별 문구 단일 원본**.
 *
 * 왜 파일 하나로 모으나: 한국어·영어·일본어 HTML 을 각각 손으로 들고 있으면 반드시
 * 어긋난다. 특히 스캐너 현황 표는 실측이 바뀔 때마다 갱신되는데, 여덟 벌을 따로 고치면
 * 한 언어만 옛 숫자를 남긴다 (AGENTS.md §9 인덱스 동기화 · §7 N-way sync 와 같은 위험).
 * 여기만 고치고 `node tools/build-hub.mjs` 를 돌리면 여덟 언어가 함께 간다.
 *
 * ⚠ **숫자는 여기서만 바꾼다.** 문구에 숫자를 하드코딩하지 말고 `stats` 를 참조하라.
 */

/** 실측 수치 — 여덟 언어가 공유한다. 값이 바뀌면 여기만 고친다. */
export const stats = {
  measuredOn: '2026-08-27',
  /*
   * ⚠ **공표 표본은 «일반 촬영» 110장이다** — 코퍼스 전체 233장이 아니다.
   *
   * 코퍼스는 성능 표본이 아니라 **실험 기록**으로 자라 왔다. 233장 중 123장은
   * 「지금 못 읽는 것」을 일부러 모아 둔 한계·실험 프레임이다:
   *   · 파인더 패턴 비교 스윕 80장 — 장마다 **다른** 파인더가 그려져 있다
   *   · 봉투 경계 프레임 24장 — 개발 문서에 「0/48 이 정상」으로 등재돼 있다
   *   · 기울기 스트레스·경계 프로브 19장
   * 이걸 섞어 세면 전체 37.3% 가 나오는데, 그건 **실험 로그를 성능으로 공표**하는
   * 것이다. 배타 근거는 배치별로 개발 문서에 남겼고, 근거를 못 찾은 배치는
   * **빼지 않고 남겼다** (v0t-20260817 = 0/6 — 그래서 Y 가 낮게 잡힌다).
   *
   * 시간도 같은 표본으로 다시 냈다. 종전 집계는 전 코퍼스 기준이라 프로브가
   * 중앙값을 끌고 갔다 (Y 는 성공 18건 중 8건이 «복호되라고 크롭한» 생존자였다).
   */
  sampleCount: 110,
  corpusTotal: 233,
  probeExcluded: 123,
  triedShortSides: '960 · 1440',
  cellFloorPx: 9,
  ultraWideFailPx: 7.6,
  wideOkPx: 9.1,
  //
  // ⚠ **«복호 시간» 은 성공한 사진의 중앙값이다** (실패는 끝까지 다 시도한 시간이라
  //   성격이 다르므로 섞지 않는다). 절대값은 측정 머신에 종속된다.
  // ⚠ **옛 게시값과 직접 비교하지 마라.** 옛 표는 사진 **9장** 기준이었고 지금은
  //   110장이다. 순위 자체가 뒤집혔다 — 옛 표의 「Type Y 약 0.1초」는 넓힌 표본에서
  //   **3.4초**다. 표본이 작을 때의 수치를 개선/악화의 근거로 쓰면 안 된다.
  // ⚠ `ms` 는 **언어별 표기 맵**이다. 숫자 표기는 en 형태를 유지한다 —
  //   소수점을 언어별 쉼표로 바꾸면 같은 수치가 생성기 사전과 다르게 보인다.
  // ⚠ **여기 «네 타입» 은 측정 범위이지 포맷의 타입 총수가 아니다.**
  //   포맷은 5종이고 (`typesTitle` = «타입 5종» · 2026-08-31 승격), 이 표가 4종인 건
  //   `measuredOn` 2026-08-27 코퍼스가 **타입 C 신설(2026-08-30)보다 앞서기 때문**이다.
  //   `rowCenterQr` 의 «네 타입» 도 같다 — 그 행은 더 옛날인 2026-08-13 라운드다.
  //   ⇒ 타입 C 가 생겼다는 이유만으로 `statusLead`·`rowCenterQr` 의 «네 타입 / all four /
  //     4 タイプ / les quatre / …» 를 5종으로 고치지 마라. **재지 않은 것을 잰 것처럼
  //     공표하게 된다.**
  //   타입 C 실기 자료가 없는 게 아니라 **축이 다르다**: PM/027 §5.10 은 라이브 스캔
  //     커버 사다리(중앙 TL 단독 C2 · 중앙 QR C0)이고, 이 표는 «정지사진 1장을 1회
  //     복호» 다. 섞으면 안 된다 ([[still-photo-is-not-live-scanning]]).
  //   고칠 때는 이 `types` 에 행을 **먼저** 넣어라 — hub-build.test.js 가 칸 수를 잠가
  //     두어서, 늘리면 여덟 언어 문구를 손보라고 실패한다.
  types: {
    Y: {
      decoded: '9 / 16',
      ms: {
        ko: '약 1.8초', en: '~1.8 s', ja: '約 1.8 秒',
        fr: '≈ 1.8 s', it: '≈ 1.8 s', de: '≈ 1.8 s', es: '≈ 1.8 s', pt: '≈ 1.8 s',
      },
    },
    O: {
      decoded: '29 / 48',
      ms: {
        ko: '약 1.9초', en: '~1.9 s', ja: '約 1.9 秒',
        fr: '≈ 1.9 s', it: '≈ 1.9 s', de: '≈ 1.9 s', es: '≈ 1.9 s', pt: '≈ 1.9 s',
      },
    },
    A: {
      decoded: '18 / 19',
      ms: {
        ko: '약 2.4초', en: '~2.4 s', ja: '約 2.4 秒',
        fr: '≈ 2.4 s', it: '≈ 2.4 s', de: '≈ 2.4 s', es: '≈ 2.4 s', pt: '≈ 2.4 s',
      },
    },
    K: {
      decoded: '18 / 27',
      ms: {
        ko: '약 3.1초', en: '~3.1 s', ja: '約 3.1 秒',
        fr: '≈ 3.1 s', it: '≈ 3.1 s', de: '≈ 3.1 s', es: '≈ 3.1 s', pt: '≈ 3.1 s',
      },
    },
  },
  // ⚠ 이 행만 **옛 라운드(9장)** 값이다 — 이번 코퍼스로는 중앙 QR 변형을 따로 가를 수
  //   없어 재측정하지 못했다. 날짜를 행에 같이 실어 출처가 섞이지 않게 한다.
  centerQr: { decoded: '8 / 9', measuredOn: '2026-08-13' },
};

/*
 * 언어판 목록 (2026-08-17: 3 → 8).
 *
 * ⚠ 이 배열이 **문서 수·hreflang·og:locale·언어 드롭다운·sitemap 을 한꺼번에 정한다.**
 *   여기에만 더하면 나머지는 따라온다 — 손으로 따로 적는 자리를 만들지 마라.
 * ⚠ `label` 은 각 언어의 **자기 표기**다. 언어를 바꾸려는 사람은 지금 화면 언어를 못
 *   읽는 사람이라, 현재 언어로 번역한 언어명은 정작 그 사람이 못 읽는다.
 * ⚠ pt 는 **pt-PT**(`pt_PT`)다. 생성기·스캐너 사전이 pt-PT 어휘로 나갔으므로
 *   (`ecrã`·`câmara`·`definições`) 여기서 pt-BR 을 선언하면 세 표면이 갈린다.
 */
export const languages = [
  { code: 'ko', dir: '', label: '한국어', ogLocale: 'ko_KR', htmlLang: 'ko' },
  { code: 'en', dir: 'en/', label: 'English', ogLocale: 'en_US', htmlLang: 'en' },
  { code: 'ja', dir: 'ja/', label: '日本語', ogLocale: 'ja_JP', htmlLang: 'ja' },
  { code: 'fr', dir: 'fr/', label: 'Français', ogLocale: 'fr_FR', htmlLang: 'fr' },
  { code: 'it', dir: 'it/', label: 'Italiano', ogLocale: 'it_IT', htmlLang: 'it' },
  { code: 'de', dir: 'de/', label: 'Deutsch', ogLocale: 'de_DE', htmlLang: 'de' },
  { code: 'es', dir: 'es/', label: 'Español', ogLocale: 'es_ES', htmlLang: 'es' },
  { code: 'pt', dir: 'pt/', label: 'Português', ogLocale: 'pt_PT', htmlLang: 'pt' },
];

export const strings = {
  ko: {
    title: 'TLcube — 휘도 순위로 데이터를 싣는 3D 바코드(실은 2.5D)',
    description: '육각 셀을 마름모 3면으로 나누고, 세 면의 상대 휘도 순서에 데이터를 싣는 오픈 3D 바코드. 스펙과 레퍼런스 구현은 Apache-2.0 으로 공개돼 있습니다.',
    ogTitle: 'TLcube — 휘도 순위로 데이터를 싣는 3D 바코드',
    ogDescription: '절대 밝기가 아니라 세 면의 순서에 데이터를 싣습니다. 조명이 흔들려도 순서만 지켜지면 살아남아요.',
    ogImageAlt: 'TLcube 배너 — 초록 Type Y 큐브 코드와 Type O·A·K 코드 석 장.',
    jsonHeadline: 'TLcube — 절대 밝기가 아니라 순서에 데이터를 싣는 3D 바코드',
    jsonDescription: '육각 셀을 마름모 3면으로 나누고 세 면의 상대 휘도 순서(3! = 6가지)를 base-6 심볼로 쓰는 오픈 3D 바코드. 단조 톤 변형에 불변합니다.',

    navWhyNow: '왜 지금',
    // 섹션 h2 가 «어떻게 동작하나» 인데 내비만 «무엇인가» 였다 — 같은 곳을 가리키는
    // 두 이름이 다르면 목차가 다른 섹션을 가리키는 것처럼 읽힌다.
    navWhat: '동작 방식', navTypes: '타입', navStatus: '스캐너 현황', navSpec: '스펙',
    navGenerator: '생성기', navScanner: '스캐너',
    themeLabel: '테마', themeAuto: '자동', themeLight: '라이트', themeDark: '다크',
    langLabel: '언어',

    heroTitle: 'QR은 잘 읽히죠.<br><strong>예뻤던 적이 없을 뿐</strong>',
    heroLead: '포스터·패키지·명함… QR이 안 들어가는 데가 없는데, 공들인 디자인 위에 마지막으로 흑백 네모를 얹는 건 늘 아쉬웠어요. 그런데 QR이 그렇게 생긴 데는 이유가 있습니다 — <strong>1994년의 카메라와 연산으로 «어떻게든 읽히게» 만든 결과</strong>거든요.',
    heroLead2: '그 제약이 지금은 많이 풀렸습니다. 카메라도 연산도 넉넉해졌죠. 그래서 인식 성능만 더 쫓는 대신 <strong>눈에 들어오는 쪽</strong>으로 한번 만들어 봤어요. QR을 대체하려는 게 아니라, <strong>옆자리를 하나</strong> 만드는 겁니다. 결과물은 <strong>3D 바코드</strong> — 평면에 인쇄되지만 눈에는 입체로 읽힙니다.',
    whyNowTitle: '왜 지금인가',
    whyNow1: '<strong>QR은 그 시절의 최선이었습니다.</strong> 흑백 두 값, 정사각 모듈, 큰 파인더 — 전부 «성능이 빠듯한 카메라로도 읽히게» 하려는 선택이었어요. 그 제약 아래서는 미감을 포기하는 게 합리적이었습니다.',
    whyNow2: '<strong>그 전제가 바뀌었어요.</strong> 지금 폰 카메라는 그때와 비교가 안 되고, 실시간 영상 처리도 브라우저 안에서 됩니다. 그러면 남는 여유를 밀도에 더 쓸 게 아니라 <strong>보이는 것</strong>에 써도 되지 않을까 — 그게 이걸 만든 이유입니다.',
    whyNow3: '<strong>대신 밀도는 포기했습니다.</strong> 마름모 셀은 정사각 모듈보다 면적 효율이 불리해요. 이 포맷은 밀도 경쟁을 하지 않습니다. 많이 담아야 하면 QR이 맞아요.',
    ctaMake: '코드 만들어보기',

    typesTitle: '타입 5종',
    typesLead: '어디에 얹을지에 따라 고르면 됩니다. 다섯 타입 모두 같은 데이터 계약을 공유하고 실루엣만 달라요. 아래 코드에는 전부 <code>https://tl.estre.so</code> 가 들어 있어요.',
    typeYName: 'Type Y — 단일 큐브',
    typeYDesc: '세 면이 각각 n×n 격자. 한 덩어리라 간판·굿즈에 어울립니다.',
    typeYMeta: 'n = 13 / 21 / 25 · 순 페이로드 31 / 98 / 141 B',
    typeOName: 'Type O — 육각 필드',
    typeODesc: '가장 기본형. 중앙 파인더를 중심으로 마름모 셀이 깔립니다.',
    typeOMeta: 'k = 6 / 8 / 10 / 12 · 순 페이로드 18 / 39 / 65 / 97 B',
    typeCName: 'Type C — 3시 노치 초대용량',
    typeCDesc: '3시 방향 노치가 실루엣만으로 방향과 타입을 확정합니다. C0~C3는 근접 스캔 전용이며, C1 이상은 가까이 대거나 확대해서 읽어야 해요.',
    typeCMeta: 'k = 14 / 16 / 18 / 20 · 순 페이로드 130 / 172 / 220 / 255 B',
    typeAName: 'Type A — 삼각 실루엣',
    typeADesc: '육각 코어에 코너 패치를 더해 정삼각형이 됩니다.',
    typeAMeta: 'k = 6 / 8 / 10 / 12 · 순 페이로드 31 / 62 / 101 B',
    typeKName: 'Type K — 육각별',
    typeKDesc: '정삼각형과 그 180° 상을 합친 별. 같은 k 에서 용량이 가장 큽니다.',
    typeKMeta: 'k = 6 / 8 / 10 / 12 · 순 페이로드 43 / 86 / 138 B',
    typesFoot: '순 페이로드는 ECC-M 기준이에요. 다섯 타입 모두 <strong>폴백 QR</strong> 을 함께 인쇄할 수 있어서, TL 코드를 못 읽는 환경에서도 최소한의 경로가 남습니다.',

    howTitle: '어떻게 동작하나',
    how1Title: '1. 셀 = 마름모 3면', how1Desc: '육각 셀을 rhombille 타일링으로 T·L·R 세 면으로 나눕니다.',
    how2Title: '2. 순서 = 심볼', how2Desc: '세 면의 휘도에 순위를 매기면 3! = 6가지 — base-6 digit 하나입니다.',
    how3Title: '3. 3 digit = 1 심볼', how3Desc: 'GF(211) 소수체 위의 Reed–Solomon 으로 오류를 정정합니다.',
    whyTitle: '무엇이 자유로워지나',
    why1: '<strong>단조 변환에 불변합니다.</strong> 전역 조명 변화·감마·프린터 톤 매핑처럼 단조 증가하는 톤 변형은 순서를 바꾸지 못합니다. 순서만 보존되면 값이 삽니다.',
    why2: '<strong>렌더러가 자유롭습니다.</strong> 데이터 계약이 "면 사이의 순서 + 최소 분리폭" 뿐이라, 그 안에서 색·질감·면 그라데이션·애니메이션이 전부 열려 있습니다. 그 자유도가 이 포맷의 핵심이에요.',
    why3: '<strong>다만 «자동으로 예뻐지는» 건 아닙니다.</strong> 자유로워지는 것은 계약이지 결과가 아니에요. 그 안에서 무엇을 그릴지는 여전히 만드는 사람 몫입니다.',

    statusTitle: '스캐너 개선 현황',
    statusLead: '<strong>디코더는 동작합니다.</strong> 네 타입 모두 실기기 사진에서 읽히고, 지금은 인식률과 속도를 끌어올리는 개선 단계예요. 아래 시간은 <strong>실기기 촬영 정지사진 한 장을 한 번 복호한 값</strong>이며, 라이브 첫 잠금 시간이나 성공률이 아니에요.',
    thType: '타입', thDecoded: '실사진 복호', thTime: '정지사진 1회 복호', thRealtime: '라이브 검증',
    rowYName: '<strong>Type Y</strong> — 단일 큐브',
    rowOName: '<strong>Type O</strong> — 육각 필드',
    rowAName: '<strong>Type A</strong> — 삼각 실루엣',
    rowKName: '<strong>Type K</strong> — 육각별',
    rowCenterQr: `<strong>중앙 QR 변형</strong> (네 타입 공통) · ${stats.centerQr.measuredOn}`,
    badgePending: '추가 측정 중',
    statusNote1: '<strong>정지사진 1회 복호 시간만으로 라이브 체감을 예측할 수 없습니다.</strong> 시험판의 초기 실기기 계측에서는 한 프레임을 빨리 처리해도 성공까지 많은 프레임이 필요하면 첫 잠금이 늦어졌고, 타입 순위도 정지사진 표와 달라졌어요. 아직 기기 한 대의 작은 표본이므로 라이브 등급은 붙이지 않고 추가 측정 중으로 표시합니다.',
    statusNote0: `<strong>정지사진 한 장을 한 번 읽는 기준</strong>입니다. 지금은 Type O가 가장 짧고 A·K·Y가 비슷하게 더 깁니다. ⚠ 이전 게시에서 «Type Y가 가장 빠르다»고 적었던 것은 사진 9장 기준이었고, 표본을 넓혀 다시 재니 <strong>순서가 뒤집혔어요</strong>. 이 수치를 라이브 첫 잠금 시간으로 읽으면 안 됩니다.`,
    statusNote2: `촬영 조건도 크게 작용합니다. 실측에서 <strong>셀당 ${stats.cellFloorPx}픽셀</strong>이 복호 하한이었고, 같은 거리라도 <strong>초광각 렌즈</strong>로 찍으면 코드가 작게 담겨 이 선 아래로 내려갔어요 (초광각 ${stats.ultraWideFailPx}px 실패 / 광각 ${stats.wideOkPx}px 성공). 스캐너에 렌즈 선택을 넣어 둔 이유입니다.`,
    statusNote3: '<strong>중앙 QR 변형</strong>은 QR 블록이 중앙 파인더 자리를 대신하고, QR의 파인더를 위치·방향 진입점으로 써서 바깥 TL 본문을 복호해요. 생성기는 이제 Type O·A·K에서 이 검증된 경로를 기본으로 사용합니다. QR은 기본적으로 리더 링크를 담는 폴백이고, 실제 페이로드는 TL 본문에 남습니다.',
    statusFoot: `측정 ${stats.measuredOn} · 표본 <strong>${stats.sampleCount}장</strong> (각 장을 ${stats.triedShortSides}px 두 해상도로 시도). ⚠ 표본은 대부분 <strong>모니터 화면을 찍은 사진</strong>이라 인쇄물·실배치 수치가 아니에요. 그리고 코퍼스 ${stats.corpusTotal}장 중 <strong>${stats.probeExcluded}장</strong>은 «지금 못 읽는 것»을 일부러 모아 둔 한계·실험 프레임이라 성능 표본에서 뺐습니다. 중앙 QR 행만 ${stats.centerQr.measuredOn} 옛 라운드 값이에요.`,

    specTitle: '스펙과 구현',
    spec1: '포맷 스펙과 레퍼런스 구현은 <strong>Apache License 2.0</strong> 으로 공개돼 있습니다. 바닐라 JavaScript, 빌드 툴체인 없음, 런타임 의존성 0 — 단일 HTML 파일로 동작합니다.',
    spec2: '<strong>디코더만 구현해도 적합 구현</strong>입니다. 확산은 읽는 쪽부터 시작하니까요.',
    ctaSpec: '포맷 스펙 읽기', ctaImpl: '레퍼런스 구현',
    thSite: '사이트', thRole: '역할', thState: '상태',
    roleGenerator: '생성기', roleScanner: '스캐너', roleHub: '소개 허브',
    stateWorking: '동작', stateHere: '여기', stateScanner: '동작 — 현황 ›',
    footerTrademark: 'QR Code is a registered trademark of DENSO WAVE INCORPORATED.',
    footerCopyright: '© 2026 SoliEstre — TrilLuminance (cube) · 코드네임 Trilume',
  },

  en: {
    title: 'TLcube — a 3D barcode (actually 2.5D) that carries data in luminance rank',
    description: 'An open 3D barcode that splits a hexagonal cell into three rhombic faces and carries data in the relative luminance order of those faces. Spec and reference implementation are published under Apache-2.0.',
    ogTitle: 'TLcube — a 3D barcode that carries data in luminance rank',
    ogDescription: 'Data rides on the order of three faces, not on absolute brightness. As long as the order survives, so does the value.',
    ogImageAlt: 'TLcube banner — a green Type Y cube code beside Type O, A and K codes.',
    jsonHeadline: 'TLcube — a 3D barcode carrying data in rank, not absolute brightness',
    jsonDescription: 'An open 3D barcode that splits a hexagonal cell into three rhombic faces and uses their relative luminance order (3! = 6) as one base-6 symbol. Invariant under monotonic tone transforms.',

    navWhyNow: 'Why now',
    navWhat: 'How it works', navTypes: 'Types', navStatus: 'Scanner status', navSpec: 'Spec',
    navGenerator: 'Generator', navScanner: 'Scanner',
    themeLabel: 'Theme', themeAuto: 'Auto', themeLight: 'Light', themeDark: 'Dark',
    langLabel: 'Language',

    heroTitle: 'QR reads well.<br>It has just never been <strong>pretty</strong>',
    heroLead: 'Posters, packaging, business cards — QR is everywhere, and dropping a black-and-white square onto a design you spent weeks on has always stung. But QR looks the way it does for a reason: it is what you build when a <strong>1994 camera and 1994 silicon</strong> have to read it at all.',
    heroLead2: 'Those constraints have largely lifted. Phone cameras and compute have room to spare now. So instead of chasing recognition alone, we spent that headroom on <strong>being worth looking at</strong>. This is not a replacement for QR — it is <strong>a seat next to it</strong>. The result is a <strong>3D barcode</strong> — printed flat, but read as solid.',
    whyNowTitle: 'Why now',
    whyNow1: '<strong>QR was the right answer for its moment.</strong> Two values, square modules, big finder patterns — every one of those choices existed so a weak camera could still read it. Under those constraints, giving up on looks was rational.',
    whyNow2: '<strong>That premise changed.</strong> Phone cameras today are nothing like those, and real-time video processing runs inside a browser. So the headroom could go into density — or it could go into <strong>how it looks</strong>. That is why this exists.',
    whyNow3: '<strong>Density was the trade.</strong> Rhombic cells are less area-efficient than square modules. This format does not compete on density. If you need to carry a lot, QR is the right tool.',
    ctaMake: 'Make a code',

    typesTitle: 'Five types',
    typesLead: 'Pick by where it will sit. All five share one data contract and differ only in silhouette. Every code below encodes <code>https://tl.estre.so</code>.',
    typeYName: 'Type Y — single cube',
    typeYDesc: 'Three n×n faces. A single solid mark, good for signage and merch.',
    typeYMeta: 'n = 13 / 21 / 25 · net payload 31 / 98 / 141 B',
    typeOName: 'Type O — hex field',
    typeODesc: 'The base form. Rhombic cells tile outward from a central finder.',
    typeOMeta: 'k = 6 / 8 / 10 / 12 · net payload 18 / 39 / 65 / 97 B',
    typeCName: 'Type C — notched ultra-capacity',
    typeCDesc: 'The 3 o’clock notch fixes both orientation and type in the silhouette. C0–C3 are for close-range scanning; bring C1 and above closer or zoom in.',
    typeCMeta: 'k = 14 / 16 / 18 / 20 · net payload 130 / 172 / 220 / 255 B',
    typeAName: 'Type A — triangular silhouette',
    typeADesc: 'A hexagonal core plus corner patches, forming an equilateral triangle.',
    typeAMeta: 'k = 6 / 8 / 10 / 12 · net payload 31 / 62 / 101 B',
    typeKName: 'Type K — Hexagram',
    typeKDesc: 'A triangle unioned with its 180° image. Largest payload at the same k.',
    typeKMeta: 'k = 6 / 8 / 10 / 12 · net payload 43 / 86 / 138 B',
    typesFoot: 'Net payload is at ECC-M. All five types can carry a <strong>fallback QR</strong> alongside, so there is still a path where a TL code cannot be read.',

    howTitle: 'How it works',
    how1Title: '1. Cell = three rhombi', how1Desc: 'A rhombille tiling splits each hexagonal cell into T, L and R faces.',
    how2Title: '2. Order = symbol', how2Desc: 'Ranking the three luminances gives 3! = 6 outcomes — one base-6 digit.',
    how3Title: '3. 3 digits = 1 symbol', how3Desc: 'Reed–Solomon over the prime field GF(211) corrects errors.',
    whyTitle: 'What this frees up',
    why1: '<strong>Invariant under monotonic transforms.</strong> Global lighting shifts, gamma, and printer tone mapping are monotonic — they cannot change an ordering. If the order survives, the value survives.',
    why2: '<strong>The renderer stays free.</strong> The data contract is only "the order between faces, plus a minimum separation". Inside that, colour, texture, per-face gradients and animation are all open. That freedom is the point of the format.',
    why3: '<strong>It does not make anything pretty on its own.</strong> What opens up is the contract, not the outcome. What you draw inside it is still your work.',

    statusTitle: 'Scanner — where it stands',
    statusLead: '<strong>The decoder works.</strong> All four types read from real-device photos; what is left is raising accuracy and speed. Each time below is <strong>one decode of one static photo taken on a real phone</strong> — not time to first lock or a live success rate.',
    thType: 'Type', thDecoded: 'Real photos decoded', thTime: 'One static-photo decode', thRealtime: 'Live validation',
    rowYName: '<strong>Type Y</strong> — single cube',
    rowOName: '<strong>Type O</strong> — hex field',
    rowAName: '<strong>Type A</strong> — triangular silhouette',
    rowKName: '<strong>Type K</strong> — hexagram',
    rowCenterQr: `<strong>Centre-QR variant</strong> (all four types) · ${stats.centerQr.measuredOn}`,
    badgePending: 'more data needed',
    statusNote1: '<strong>One static-photo decode time does not predict how live scanning feels.</strong> In the first real-device lab trace, a fast frame could still lead to a slow first lock when many frames were needed before one succeeded, and the type ranking differed from this static-photo table. That trace covers one device and a small sample, so we do not assign live usability grades yet.',
    statusNote0: `<strong>One decode of one still photo.</strong> Type O is now the fastest; A, K and Y sit close together behind it. ⚠ An earlier version of this page said Type Y was the fastest — that was a 9-photo sample, and on a wider sample the <strong>order flipped</strong>. Do not read these as live first-lock times.`,
    statusNote2: `Shooting conditions matter too. Measured, <strong>${stats.cellFloorPx} pixels per cell</strong> was the decode floor, and at the same distance an <strong>ultra-wide lens</strong> frames the code smaller and drops below that line (ultra-wide ${stats.ultraWideFailPx} px failed / wide ${stats.wideOkPx} px succeeded). That is why the scanner offers a lens picker.`,
    statusNote3: 'In the <strong>centre-QR variant</strong>, a QR block replaces the central finder. Its finder patterns provide the position and orientation entry point used to decode the surrounding TL body. The generator now uses this validated path by default for Types O and A. By default the QR remains a reader-link fallback; the payload stays in the TL body.',
    statusFoot: `Measured ${stats.measuredOn} · sample of <strong>${stats.sampleCount} photos</strong> (each tried at ${stats.triedShortSides} px short side). ⚠ Most of the sample is <strong>photographed off a monitor</strong>, so these are not print or in-situ numbers. And ${stats.probeExcluded} of the ${stats.corpusTotal} corpus frames are limit/experiment shots kept precisely because they do not decode yet — they are excluded here. Only the centre-QR row is from the older ${stats.centerQr.measuredOn} round.`,

    specTitle: 'Spec and implementation',
    spec1: 'The format spec and reference implementation are published under the <strong>Apache License 2.0</strong>. Vanilla JavaScript, no build toolchain, zero runtime dependencies — it runs as a single HTML file.',
    spec2: '<strong>Implementing only the decoder counts as a conforming implementation.</strong> Adoption starts with the reading side.',
    ctaSpec: 'Read the spec', ctaImpl: 'Reference implementation',
    thSite: 'Site', thRole: 'Role', thState: 'State',
    roleGenerator: 'Generator', roleScanner: 'Scanner', roleHub: 'Overview hub',
    stateWorking: 'live', stateHere: 'you are here', stateScanner: 'live — status ›',
    footerTrademark: 'QR Code is a registered trademark of DENSO WAVE INCORPORATED.',
    footerCopyright: '© 2026 SoliEstre — TrilLuminance (cube) · codename Trilume',
  },

  ja: {
    title: 'TLcube — 輝度の順序でデータを載せる3Dバーコード（実際は2.5D）',
    description: '六角形のセルを 3 つの菱形の面に分け、面どうしの相対輝度の順序にデータを載せるオープンな3Dバーコード。仕様とリファレンス実装は Apache-2.0 で公開しています。',
    ogTitle: 'TLcube — 輝度の順序でデータを載せる3Dバーコード',
    ogDescription: '絶対的な明るさではなく、3 面の順序にデータを載せます。順序さえ保たれれば値は生き残ります。',
    ogImageAlt: 'TLcube バナー — 緑の Type Y キューブコードと Type O・A・K のコード 3 枚。',
    jsonHeadline: 'TLcube — 絶対輝度ではなく順序にデータを載せる3Dバーコード',
    jsonDescription: '六角形のセルを 3 つの菱形の面に分け、その相対輝度の順序（3! = 6 通り）を base-6 シンボル 1 つとして使うオープンな3Dバーコード。単調なトーン変換に対して不変です。',

    navWhyNow: 'なぜ今',
    navWhat: '仕組み', navTypes: 'タイプ', navStatus: 'スキャナ状況', navSpec: '仕様',
    navGenerator: 'ジェネレータ', navScanner: 'スキャナ',
    themeLabel: 'テーマ', themeAuto: '自動', themeLight: 'ライト', themeDark: 'ダーク',
    langLabel: '言語',

    heroTitle: 'QR はよく読めます。<br>ただ<strong>綺麗だった試しがない</strong>',
    heroLead: 'ポスター、パッケージ、名刺 — QR が入らない場所はほとんどありません。けれど何週間もかけたデザインの上に、最後に白黒の四角を置くのはいつも心残りでした。とはいえ QR があの形なのには理由があります。<strong>1994 年のカメラと演算で「とにかく読める」ようにした結果</strong>なのです。',
    heroLead2: 'その制約はもうかなり緩みました。カメラも演算も余裕があります。そこで認識性能をさらに追うかわりに、その余裕を<strong>見て気持ちのいいもの</strong>に使ってみました。QR を置き換えるためではなく、<strong>隣にもう一席</strong>つくるためのものです。 できあがるのは<strong>3Dバーコード</strong>——平面に印刷されますが、目には立体に見えます。',
    whyNowTitle: 'なぜ今なのか',
    whyNow1: '<strong>QR は当時の最適解でした。</strong>白黒の 2 値、正方モジュール、大きなファインダ — どれも性能の限られたカメラでも読めるようにするための選択です。その制約の下では、見た目を諦めるのは合理的でした。',
    whyNow2: '<strong>その前提が変わりました。</strong>いまのスマートフォンのカメラは当時とは比べものにならず、リアルタイムの映像処理がブラウザの中で動きます。ならばその余裕を密度にではなく、<strong>見え方</strong>に使ってもいいのではないか — それがこれを作った理由です。',
    whyNow3: '<strong>代わりに密度は捨てました。</strong>菱形セルは正方モジュールより面積効率で不利です。このフォーマットは密度で競いません。たくさん詰め込みたいなら QR が適しています。',
    ctaMake: 'コードを作ってみる',

    typesTitle: 'タイプ5種',
    typesLead: 'どこに載せるかで選んでください。5 タイプとも同じデータ契約を共有し、シルエットだけが異なります。以下のコードにはすべて <code>https://tl.estre.so</code> が入っています。',
    typeYName: 'Type Y — 単一キューブ',
    typeYDesc: '3 面がそれぞれ n×n の格子。ひと塊なので看板やグッズに向きます。',
    typeYMeta: 'n = 13 / 21 / 25 · 正味ペイロード 31 / 98 / 141 B',
    typeOName: 'Type O — 六角フィールド',
    typeODesc: '最も基本の形。中央のファインダを中心に菱形セルが広がります。',
    typeOMeta: 'k = 6 / 8 / 10 / 12 · 正味ペイロード 18 / 39 / 65 / 97 B',
    typeCName: 'Type C — 3時ノッチの超大容量',
    typeCDesc: '3時方向のノッチが、シルエットだけで向きとタイプを確定します。C0〜C3は近距離スキャン専用で、C1以上は近づけるか拡大して読み取ります。',
    typeCMeta: 'k = 14 / 16 / 18 / 20 · 正味ペイロード 130 / 172 / 220 / 255 B',
    typeAName: 'Type A — 三角シルエット',
    typeADesc: '六角のコアにコーナーパッチを足して正三角形になります。',
    typeAMeta: 'k = 6 / 8 / 10 / 12 · 正味ペイロード 31 / 62 / 101 B',
    typeKName: 'Type K — 六芒星',
    typeKDesc: '正三角形とその180°像を合わせた星。同じ k で容量が最大です。',
    typeKMeta: 'k = 6 / 8 / 10 / 12 · 正味ペイロード 43 / 86 / 138 B',
    typesFoot: '正味ペイロードは ECC-M 基準です。5 タイプとも<strong>フォールバック QR</strong> を併記でき、TL コードが読めない環境でも最低限の経路が残ります。',

    howTitle: '仕組み',
    how1Title: '1. セル = 3 つの菱形', how1Desc: 'rhombille タイリングで六角セルを T・L・R の 3 面に分けます。',
    how2Title: '2. 順序 = シンボル', how2Desc: '3 面の輝度に順位をつけると 3! = 6 通り — base-6 の 1 桁です。',
    how3Title: '3. 3 桁 = 1 シンボル', how3Desc: '素体 GF(211) 上の Reed–Solomon で誤りを訂正します。',
    whyTitle: '何が自由になるのか',
    why1: '<strong>単調変換に対して不変です。</strong> 全体的な照明の変化・ガンマ・プリンタのトーンマッピングは単調なので、順序を入れ替えられません。順序が保たれれば値は生きます。',
    why2: '<strong>レンダラが自由です。</strong> データ契約は「面どうしの順序 + 最小分離幅」だけ。その中で色・質感・面のグラデーション・アニメーションがすべて開いています。この自由度こそがこのフォーマットの核心です。',
    why3: '<strong>ただし「自動できれいになる」わけではありません。</strong>自由になるのは契約であって結果ではありません。その中で何を描くかは作り手の仕事のままです。',

    statusTitle: 'スキャナ改善状況',
    statusLead: '<strong>デコーダは動作します。</strong>4 タイプとも実機の写真から読めており、いまは認識率と速度を上げる改善段階です。以下の時間は<strong>実機で撮影した静止画 1 枚を 1 回復号した値</strong>で、ライブの初回ロック時間や成功率ではありません。',
    thType: 'タイプ', thDecoded: '実写真の復号', thTime: '静止画 1 回の復号', thRealtime: 'ライブ検証',
    rowYName: '<strong>Type Y</strong> — 単一キューブ',
    rowOName: '<strong>Type O</strong> — 六角フィールド',
    rowAName: '<strong>Type A</strong> — 三角シルエット',
    rowKName: '<strong>Type K</strong> — 六芒星',
    rowCenterQr: `<strong>中央 QR 変種</strong>（4 タイプ共通） · ${stats.centerQr.measuredOn}`,
    badgePending: '追加測定中',
    statusNote1: '<strong>静止画 1 回の復号時間だけではライブの体感を予測できません。</strong>試験版の初期実機計測では、1 フレームが速くても成功までに多くのフレームを要すると初回ロックが遅くなり、タイプの順序も静止画の表とは異なりました。まだ 1 台の小さな標本なので、ライブの実用性評価は付けず追加測定中としています。',
    statusNote0: `<strong>静止画 1 枚を 1 回読む基準</strong>です。現在は Type O が最も短く、A・K・Y はその後ろで近い値です。⚠ 以前の掲載で「Type Y が最速」と書いたのは写真 9 枚の標本で、標本を広げて測り直すと<strong>順序が逆転</strong>しました。ライブの初回ロック時間として読まないでください。`,
    statusNote2: `撮影条件も大きく効きます。実測では<strong>セルあたり ${stats.cellFloorPx} ピクセル</strong>が復号の下限で、同じ距離でも<strong>超広角レンズ</strong>で撮るとコードが小さく写ってこの線を下回りました（超広角 ${stats.ultraWideFailPx}px 失敗 / 広角 ${stats.wideOkPx}px 成功）。スキャナにレンズ選択を入れているのはそのためです。`,
    statusNote3: '<strong>中央 QR 変種</strong>では QR ブロックが中央ファインダを置き換え、QR のファインダを位置・方向の入口として周囲の TL 本文を復号します。ジェネレータは Type O・A・K でこの検証済み経路を標準にしました。QR は既定ではリーダーリンクのフォールバックで、ペイロード自体は TL 本文に残ります。',
    statusFoot: `測定 ${stats.measuredOn} · 標本 <strong>${stats.sampleCount} 枚</strong>（各枚を短辺 ${stats.triedShortSides}px の 2 解像度で試行）。⚠ 標本の大半は<strong>モニター画面を撮った写真</strong>で、印刷物や実配置の数値ではありません。またコーパス ${stats.corpusTotal} 枚のうち <strong>${stats.probeExcluded} 枚</strong>は「今は読めないもの」を意図的に集めた限界・実験フレームなので、性能標本から除いています。中央 QR の行だけ ${stats.centerQr.measuredOn} の旧ラウンド値です。`,

    specTitle: '仕様と実装',
    spec1: 'フォーマット仕様とリファレンス実装は <strong>Apache License 2.0</strong> で公開しています。バニラ JavaScript、ビルドツールチェーンなし、ランタイム依存 0 — 単一の HTML ファイルで動きます。',
    spec2: '<strong>デコーダだけの実装でも適合実装</strong>とみなします。普及は読む側から始まるからです。',
    ctaSpec: '仕様を読む', ctaImpl: 'リファレンス実装',
    thSite: 'サイト', thRole: '役割', thState: '状態',
    roleGenerator: 'ジェネレータ', roleScanner: 'スキャナ', roleHub: '紹介ハブ',
    stateWorking: '稼働中', stateHere: 'ここ', stateScanner: '稼働中 — 状況 ›',
    footerTrademark: 'QR Code is a registered trademark of DENSO WAVE INCORPORATED.',
    footerCopyright: '© 2026 SoliEstre — TrilLuminance (cube) · コードネーム Trilume',
  },

  /* fr — vouvoiement. 상표 고지(footerTrademark)는 법적 문구라 전 언어 영어 원문 유지. */
  fr: {
    title: 'TLcube — un code-barres 3D (en réalité 2.5D) qui porte les données dans le rang de luminance',
    description: 'Un code-barres 3D ouvert qui divise une cellule hexagonale en trois faces en losange et porte les données dans l\'ordre de luminance relative de ces faces. La spécification et l\'implémentation de référence sont publiées sous Apache-2.0.',
    ogTitle: 'TLcube — un code-barres 3D qui porte les données dans le rang de luminance',
    ogDescription: 'Les données reposent sur l\'ordre des trois faces, pas sur la luminosité absolue. Tant que l\'ordre survit, la valeur survit.',
    ogImageAlt: 'Bannière TLcube — un code cube Type Y vert à côté des codes Type O, A et K.',
    jsonHeadline: 'TLcube — un code-barres 3D qui porte les données dans le rang, non dans la luminosité absolue',
    jsonDescription: 'Un code-barres 3D ouvert qui divise une cellule hexagonale en trois faces en losange et utilise leur ordre de luminance relative (3! = 6) comme un symbole en base 6. Invariant par transformation tonale monotone.',

    navWhyNow: 'Pourquoi maintenant',
    navWhat: 'Fonctionnement', navTypes: 'Types', navStatus: 'État du scanner', navSpec: 'Spécification',
    navGenerator: 'Générateur', navScanner: 'Scanner',
    themeLabel: 'Thème', themeAuto: 'Auto', themeLight: 'Clair', themeDark: 'Sombre',
    langLabel: 'Langue',

    heroTitle: 'Le QR se lit bien.<br>Il n\'a simplement jamais été <strong>beau</strong>',
    heroLead: 'Affiches, emballages, cartes de visite — le QR est partout, et poser un carré noir et blanc sur un design longuement travaillé a toujours laissé un regret. Mais s\'il a cette allure, c\'est pour une raison : c\'est ce qu\'on construit quand <strong>une caméra et un processeur de 1994</strong> doivent pouvoir le lire.',
    heroLead2: 'Ces contraintes se sont largement levées. Les caméras de téléphone et la puissance de calcul ont de la marge. Alors, plutôt que de courir après la seule reconnaissance, nous avons dépensé cette marge du côté du <strong>plaisir des yeux</strong>. Il ne s\'agit pas de remplacer le QR, mais de lui <strong>ajouter un siège voisin</strong>. Le résultat est un <strong>code-barres 3D</strong> — imprimé à plat, mais perçu en relief.',
    whyNowTitle: 'Pourquoi maintenant',
    whyNow1: '<strong>Le QR était la bonne réponse à son époque.</strong> Deux valeurs, des modules carrés, de grands motifs de repérage — chacun de ces choix existait pour qu\'une caméra faible puisse tout de même lire. Sous ces contraintes, renoncer à l\'esthétique était rationnel.',
    whyNow2: '<strong>Cette prémisse a changé.</strong> Les caméras de téléphone d\'aujourd\'hui n\'ont plus rien à voir, et le traitement vidéo en temps réel tourne dans un navigateur. Cette marge pouvait aller à la densité — ou à <strong>l\'apparence</strong>. C\'est la raison d\'être de ce format.',
    whyNow3: '<strong>La densité, elle, a été sacrifiée.</strong> Les cellules en losange sont moins efficaces en surface que les modules carrés. Ce format ne concourt pas sur la densité. S\'il faut transporter beaucoup, le QR reste l\'outil adapté.',
    ctaMake: 'Créer un code',

    typesTitle: 'Cinq types',
    typesLead: 'Choisissez selon l\'endroit où il sera posé. Les cinq partagent le même contrat de données et ne diffèrent que par la silhouette. Tous les codes ci-dessous encodent <code>https://tl.estre.so</code>.',
    typeYName: 'Type Y — cube unique',
    typeYDesc: 'Trois faces n×n. Une marque d\'un seul tenant, adaptée à la signalétique et aux objets.',
    typeYMeta: 'n = 13 / 21 / 25 · charge utile nette 31 / 98 / 141 B',
    typeOName: 'Type O — champ hexagonal',
    typeODesc: 'La forme de base. Les cellules en losange se déploient autour d\'un repère central.',
    typeOMeta: 'k = 6 / 8 / 10 / 12 · charge utile nette 18 / 39 / 65 / 97 B',
    typeCName: 'Type C — ultra-haute capacité à encoche',
    typeCDesc: 'L’encoche à 3 h fixe l’orientation et le type dans la silhouette elle-même. La gamme C0–C3 est réservée au scan rapproché ; à partir de C1, rapprochez le code ou zoomez.',
    typeCMeta: 'k = 14 / 16 / 18 / 20 · charge utile nette 130 / 172 / 220 / 255 B',
    typeAName: 'Type A — silhouette triangulaire',
    typeADesc: 'Un cœur hexagonal complété de pièces d\'angle, formant un triangle équilatéral.',
    typeAMeta: 'k = 6 / 8 / 10 / 12 · charge utile nette 31 / 62 / 101 B',
    typeKName: 'Type K — Hexagramme',
    typeKDesc: 'Un triangle uni à son image à 180°. Charge utile la plus grande à k égal.',
    typeKMeta: 'k = 6 / 8 / 10 / 12 · charge utile nette 43 / 86 / 138 B',
    typesFoot: 'La charge utile nette est donnée pour ECC-M. Les cinq types peuvent porter un <strong>QR de secours</strong> à côté, si bien qu\'il reste un chemin là où un code TL ne peut pas être lu.',

    howTitle: 'Fonctionnement',
    how1Title: '1. Cellule = trois losanges', how1Desc: 'Un pavage rhombille divise chaque cellule hexagonale en faces T, L et R.',
    how2Title: '2. Ordre = symbole', how2Desc: 'Classer les trois luminances donne 3! = 6 résultats — un chiffre en base 6.',
    how3Title: '3. 3 chiffres = 1 symbole', how3Desc: 'Un Reed–Solomon sur le corps premier GF(211) corrige les erreurs.',
    whyTitle: 'Ce que cela libère',
    why1: '<strong>Invariant par transformation monotone.</strong> Les changements d\'éclairage global, le gamma et la table tonale d\'une imprimante sont monotones — ils ne peuvent pas changer un ordre. Si l\'ordre survit, la valeur survit.',
    why2: '<strong>Le rendu reste libre.</strong> Le contrat de données se réduit à « l\'ordre entre les faces, plus un écart minimal ». À l\'intérieur, la couleur, la matière, les dégradés par face et l\'animation sont ouverts. Cette liberté est le cœur du format.',
    why3: '<strong>Cela ne rend rien beau tout seul.</strong> Ce qui s\'ouvre, c\'est le contrat, pas le résultat. Ce que vous dessinez à l\'intérieur reste votre travail.',

    statusTitle: 'Scanner — où nous en sommes',
    statusLead: '<strong>Le décodeur fonctionne.</strong> Les quatre types se lisent sur des photos prises avec de vrais appareils ; reste à faire monter la précision et la vitesse. Chaque temps ci-dessous correspond à <strong>un décodage d\'une photo fixe prise avec un vrai téléphone</strong> — ce n\'est ni un temps de premier accrochage ni un taux de réussite en direct.',
    thType: 'Type', thDecoded: 'Photos réelles décodées', thTime: 'Un décodage sur photo fixe', thRealtime: 'Validation en direct',
    rowYName: '<strong>Type Y</strong> — cube unique',
    rowOName: '<strong>Type O</strong> — champ hexagonal',
    rowAName: '<strong>Type A</strong> — silhouette triangulaire',
    rowKName: '<strong>Type K</strong> — hexagramme',
    rowCenterQr: `<strong>Variante QR central</strong> (les quatre types) · ${stats.centerQr.measuredOn}`,
    badgePending: 'mesures en cours',
    statusNote1: '<strong>Le temps d\'un décodage sur photo fixe ne prédit pas le ressenti d\'un scan en direct.</strong> Lors des premières mesures sur appareil réel, une image rapide pouvait tout de même donner un premier accrochage lent lorsqu\'il fallait beaucoup d\'images avant une réussite, et le classement des types différait de ce tableau sur photo fixe. Ces relevés portent sur un seul appareil et un petit échantillon : nous n\'attribuons donc pas encore de note d\'usage en direct.',
    statusNote0: `<strong>Un décodage d’une seule photo fixe.</strong> Le Type O est désormais le plus rapide ; A, K et Y sont proches derrière. ⚠ Une version antérieure de cette page annonçait le Type Y comme le plus rapide : c’était un échantillon de 9 photos, et sur un échantillon élargi l’<strong>ordre s’est inversé</strong>. Ne lisez pas ces valeurs comme des temps de premier verrouillage en direct.`,
    statusNote2: `Les conditions de prise de vue comptent aussi. À la mesure, <strong>${stats.cellFloorPx} pixels par cellule</strong> était le plancher de décodage, et à distance égale un <strong>objectif ultra grand-angle</strong> cadre le code plus petit et passe sous cette ligne (ultra grand-angle ${stats.ultraWideFailPx} px en échec / grand-angle ${stats.wideOkPx} px en réussite). C\'est pourquoi le scanner propose un choix d\'objectif.`,
    statusNote3: 'Dans la <strong>variante QR central</strong>, un bloc QR remplace le repère central. Ses motifs de repérage fournissent le point d\'entrée en position et en orientation qui sert à décoder le corps TL environnant. Le générateur utilise désormais ce chemin validé par défaut pour les types O et A. Par défaut, le QR reste un secours qui porte un lien de lecture ; la charge utile, elle, reste dans le corps TL.',
    statusFoot: `Mesuré le ${stats.measuredOn} · échantillon de <strong>${stats.sampleCount} photos</strong> (chacune essayée en ${stats.triedShortSides} px de petit côté). ⚠ L’essentiel de l’échantillon est <strong>photographié sur un écran</strong> : ce ne sont pas des chiffres d’impression ni de mise en situation. Et ${stats.probeExcluded} des ${stats.corpusTotal} images du corpus sont des prises limites conservées justement parce qu’elles ne se décodent pas encore — elles sont exclues ici. Seule la ligne QR central provient de la campagne du ${stats.centerQr.measuredOn}.`,

    specTitle: 'Spécification et implémentation',
    spec1: 'La spécification du format et l\'implémentation de référence sont publiées sous <strong>licence Apache 2.0</strong>. JavaScript vanilla, aucune chaîne de build, zéro dépendance à l\'exécution — cela tourne dans un seul fichier HTML.',
    spec2: '<strong>N\'implémenter que le décodeur suffit à être une implémentation conforme.</strong> L\'adoption commence par le côté lecture.',
    ctaSpec: 'Lire la spécification', ctaImpl: 'Implémentation de référence',
    thSite: 'Site', thRole: 'Rôle', thState: 'État',
    roleGenerator: 'Générateur', roleScanner: 'Scanner', roleHub: 'Site de présentation',
    stateWorking: 'en ligne', stateHere: 'vous êtes ici', stateScanner: 'en ligne — état ›',
    footerTrademark: 'QR Code is a registered trademark of DENSO WAVE INCORPORATED.',
    footerCopyright: '© 2026 SoliEstre — TrilLuminance (cube) · nom de code Trilume',
  },

  it: {
    title: 'TLcube — un codice a barre 3D (in realtà 2.5D) che porta i dati nel rango di luminanza',
    description: 'Un codice a barre 3D aperto che divide una cella esagonale in tre facce romboidali e porta i dati nell\'ordine di luminanza relativa di quelle facce. Specifica e implementazione di riferimento sono pubblicate con licenza Apache-2.0.',
    ogTitle: 'TLcube — un codice a barre 3D che porta i dati nel rango di luminanza',
    ogDescription: 'I dati poggiano sull\'ordine delle tre facce, non sulla luminosità assoluta. Finché sopravvive l\'ordine, sopravvive il valore.',
    ogImageAlt: 'Banner TLcube — un codice cubo Type Y verde accanto ai codici Type O, A e K.',
    jsonHeadline: 'TLcube — un codice a barre 3D che porta i dati nel rango, non nella luminosità assoluta',
    jsonDescription: 'Un codice a barre 3D aperto che divide una cella esagonale in tre facce romboidali e usa il loro ordine di luminanza relativa (3! = 6) come un simbolo in base 6. Invariante rispetto alle trasformazioni tonali monotone.',

    navWhyNow: 'Perché ora',
    navWhat: 'Come funziona', navTypes: 'Tipi', navStatus: 'Stato dello scanner', navSpec: 'Specifica',
    navGenerator: 'Generatore', navScanner: 'Scanner',
    themeLabel: 'Tema', themeAuto: 'Auto', themeLight: 'Chiaro', themeDark: 'Scuro',
    langLabel: 'Lingua',

    heroTitle: 'Il QR si legge bene.<br>Non è mai stato <strong>bello</strong>',
    heroLead: 'Manifesti, confezioni, biglietti da visita — il QR è ovunque, e mettere un quadrato in bianco e nero sopra un progetto curato per settimane è sempre stato un dispiacere. Ma il QR ha quell\'aspetto per un motivo: è ciò che si costruisce quando <strong>una fotocamera e un processore del 1994</strong> devono riuscire a leggerlo.',
    heroLead2: 'Quei vincoli sono in gran parte caduti. Le fotocamere dei telefoni e la potenza di calcolo hanno margine. Così, invece di rincorrere solo il riconoscimento, quel margine è stato speso perché il codice <strong>valga la pena di essere guardato</strong>. Non è un sostituto del QR: è <strong>un posto accanto</strong>. Il risultato è un <strong>codice a barre 3D</strong> — stampato in piano, ma percepito in rilievo.',
    whyNowTitle: 'Perché proprio ora',
    whyNow1: '<strong>Il QR era la risposta giusta per il suo tempo.</strong> Due valori, moduli quadrati, grandi pattern di ricerca — ognuna di quelle scelte serviva a far leggere il codice anche a una fotocamera debole. Con quei vincoli, rinunciare all\'estetica era razionale.',
    whyNow2: '<strong>Quella premessa è cambiata.</strong> Le fotocamere dei telefoni di oggi non hanno nulla a che vedere con quelle, e l\'elaborazione video in tempo reale gira dentro un browser. Quel margine poteva andare alla densità — oppure a <strong>come appare</strong>. È per questo che il formato esiste.',
    whyNow3: '<strong>In cambio si è rinunciato alla densità.</strong> Le celle romboidali sono meno efficienti in superficie dei moduli quadrati. Questo formato non compete sulla densità. Se serve trasportare molto, lo strumento giusto resta il QR.',
    ctaMake: 'Crea un codice',

    typesTitle: 'Cinque tipi',
    typesLead: 'Scegli in base a dove verrà messo. Tutti e cinque condividono lo stesso contratto dati e differiscono solo per la silhouette. Ogni codice qui sotto contiene <code>https://tl.estre.so</code>.',
    typeYName: 'Type Y — cubo singolo',
    typeYDesc: 'Tre facce n×n. Un segno compatto, adatto a insegne e gadget.',
    typeYMeta: 'n = 13 / 21 / 25 · payload netto 31 / 98 / 141 B',
    typeOName: 'Type O — campo esagonale',
    typeODesc: 'La forma base. Le celle romboidali si dispongono attorno a un pattern di ricerca centrale.',
    typeOMeta: 'k = 6 / 8 / 10 / 12 · payload netto 18 / 39 / 65 / 97 B',
    typeCName: 'Type C — capacità ultra con tacca',
    typeCDesc: 'La tacca a ore 3 fissa orientamento e tipo nella silhouette stessa. La gamma C0–C3 è per scansioni ravvicinate; da C1 in su, avvicina il codice o usa lo zoom.',
    typeCMeta: 'k = 14 / 16 / 18 / 20 · payload netto 130 / 172 / 220 / 255 B',
    typeAName: 'Type A — silhouette triangolare',
    typeADesc: 'Un nucleo esagonale più le toppe d\'angolo, che formano un triangolo equilatero.',
    typeAMeta: 'k = 6 / 8 / 10 / 12 · payload netto 31 / 62 / 101 B',
    typeKName: 'Type K — Esagramma',
    typeKDesc: 'Un triangolo unito alla sua immagine a 180°. Massima capacità a parità di k.',
    typeKMeta: 'k = 6 / 8 / 10 / 12 · payload netto 43 / 86 / 138 B',
    typesFoot: 'Il payload netto è riferito a ECC-M. Tutti e cinque i tipi possono portare accanto un <strong>QR di riserva</strong>, così resta una via anche dove il codice TL non è leggibile.',

    howTitle: 'Come funziona',
    how1Title: '1. Cella = tre rombi', how1Desc: 'Una tassellatura rhombille divide ogni cella esagonale nelle facce T, L e R.',
    how2Title: '2. Ordine = simbolo', how2Desc: 'Ordinare le tre luminanze dà 3! = 6 esiti — una cifra in base 6.',
    how3Title: '3. 3 cifre = 1 simbolo', how3Desc: 'Un Reed–Solomon sul campo primo GF(211) corregge gli errori.',
    whyTitle: 'Che cosa si libera',
    why1: '<strong>Invariante rispetto alle trasformazioni monotone.</strong> Variazioni di luce globale, gamma e mappatura tonale della stampante sono monotone: non possono cambiare un ordinamento. Se l\'ordine sopravvive, il valore sopravvive.',
    why2: '<strong>Il renderer resta libero.</strong> Il contratto dati è solo «l\'ordine fra le facce, più una separazione minima». Dentro quel vincolo, colore, texture, gradienti per faccia e animazione sono tutti aperti. Quella libertà è il senso del formato.',
    why3: '<strong>Non rende però nulla bello da solo.</strong> Ciò che si apre è il contratto, non il risultato. Che cosa disegnare lì dentro resta lavoro di chi progetta.',

    statusTitle: 'Scanner — a che punto siamo',
    statusLead: '<strong>Il decoder funziona.</strong> Tutti e tre i tipi si leggono da foto scattate con dispositivi reali; resta da alzare precisione e velocità. Ogni tempo qui sotto è <strong>una decodifica di una singola foto statica scattata con un telefono reale</strong>, non il tempo del primo aggancio né un tasso di successo dal vivo.',
    thType: 'Tipo', thDecoded: 'Foto reali decodificate', thTime: 'Una decodifica su foto statica', thRealtime: 'Verifica dal vivo',
    rowYName: '<strong>Type Y</strong> — cubo singolo',
    rowOName: '<strong>Type O</strong> — campo esagonale',
    rowAName: '<strong>Type A</strong> — silhouette triangolare',
    rowKName: '<strong>Type K</strong> — esagramma',
    rowCenterQr: `<strong>Variante QR centrale</strong> (tutti e quattro i tipi) · ${stats.centerQr.measuredOn}`,
    badgePending: 'altre misure in corso',
    statusNote1: '<strong>Il tempo di una decodifica su foto statica non predice la sensazione della scansione dal vivo.</strong> Nelle prime misure su dispositivo reale, un fotogramma veloce poteva comunque portare a un primo aggancio lento quando servivano molti fotogrammi prima di uno riuscito, e la classifica dei tipi risultava diversa da questa tabella su foto statica. Quei rilievi riguardano un solo dispositivo e un campione piccolo, quindi non assegniamo ancora un giudizio d\'uso dal vivo.',
    statusNote0: `<strong>Una decodifica di una singola foto ferma.</strong> Il Type O è ora il più rapido; A, K e Y stanno vicini subito dietro. ⚠ Una versione precedente di questa pagina indicava il Type Y come il più rapido: era un campione di 9 foto e, su un campione più ampio, l’<strong>ordine si è ribaltato</strong>. Non leggeteli come tempi di primo aggancio dal vivo.`,
    statusNote2: `Contano molto anche le condizioni di ripresa. Alla misura, <strong>${stats.cellFloorPx} pixel per cella</strong> era il limite inferiore di decodifica e, a parità di distanza, un <strong>obiettivo ultragrandangolare</strong> inquadra il codice più piccolo e scende sotto quella soglia (ultragrandangolare ${stats.ultraWideFailPx} px fallito / grandangolare ${stats.wideOkPx} px riuscito). Per questo lo scanner offre la scelta dell\'obiettivo.`,
    statusNote3: 'Nella <strong>variante con QR centrale</strong> un blocco QR sostituisce il pattern di ricerca centrale. I suoi pattern forniscono il punto d\'ingresso di posizione e orientamento con cui si decodifica il corpo TL circostante. Il generatore usa ora questo percorso verificato come impostazione predefinita per i tipi O e A. Per impostazione predefinita il QR resta una riserva che porta un link al lettore; il payload vero rimane nel corpo TL.',
    statusFoot: `Misurato il ${stats.measuredOn} · campione di <strong>${stats.sampleCount} foto</strong> (ognuna provata a ${stats.triedShortSides} px di lato corto). ⚠ Gran parte del campione è <strong>fotografata da uno schermo</strong>: non sono numeri di stampa né di posa reale. Inoltre ${stats.probeExcluded} dei ${stats.corpusTotal} fotogrammi del corpus sono scatti al limite tenuti proprio perché non si decodificano ancora — qui sono esclusi. Solo la riga QR centrale viene dal ciclo precedente del ${stats.centerQr.measuredOn}.`,

    specTitle: 'Specifica e implementazione',
    spec1: 'La specifica del formato e l\'implementazione di riferimento sono pubblicate con <strong>licenza Apache 2.0</strong>. JavaScript puro, nessuna toolchain di build, zero dipendenze a runtime — funziona come un singolo file HTML.',
    spec2: '<strong>Implementare solo il decoder basta a essere un\'implementazione conforme.</strong> La diffusione parte da chi legge.',
    ctaSpec: 'Leggi la specifica', ctaImpl: 'Implementazione di riferimento',
    thSite: 'Sito', thRole: 'Ruolo', thState: 'Stato',
    roleGenerator: 'Generatore', roleScanner: 'Scanner', roleHub: 'Sito di presentazione',
    stateWorking: 'attivo', stateHere: 'sei qui', stateScanner: 'attivo — stato ›',
    footerTrademark: 'QR Code is a registered trademark of DENSO WAVE INCORPORATED.',
    footerCopyright: '© 2026 SoliEstre — TrilLuminance (cube) · nome in codice Trilume',
  },

  /* de — Siezen. 명사는 대문자, 합성어는 붙여 쓰거나 하이픈으로 잇는다. */
  de: {
    title: 'TLcube — ein 3D-Barcode (eigentlich 2.5D), der Daten im Luminanzrang trägt',
    description: 'Ein offener 3D-Barcode, der eine sechseckige Zelle in drei rautenförmige Flächen teilt und die Daten in der relativen Luminanzreihenfolge dieser Flächen trägt. Spezifikation und Referenzimplementierung sind unter Apache-2.0 veröffentlicht.',
    ogTitle: 'TLcube — ein 3D-Barcode, der Daten im Luminanzrang trägt',
    ogDescription: 'Die Daten liegen in der Reihenfolge der drei Flächen, nicht in der absoluten Helligkeit. Solange die Reihenfolge überlebt, überlebt der Wert.',
    ogImageAlt: 'TLcube-Banner — ein grüner Type-Y-Würfelcode neben den Codes Type O, A und K.',
    jsonHeadline: 'TLcube — ein 3D-Barcode, der Daten im Rang statt in absoluter Helligkeit trägt',
    jsonDescription: 'Ein offener 3D-Barcode, der eine sechseckige Zelle in drei rautenförmige Flächen teilt und deren relative Luminanzreihenfolge (3! = 6) als ein Symbol zur Basis 6 nutzt. Invariant gegenüber monotonen Tonwertänderungen.',

    navWhyNow: 'Warum jetzt',
    navWhat: 'Funktionsweise', navTypes: 'Typen', navStatus: 'Stand des Scanners', navSpec: 'Spezifikation',
    navGenerator: 'Generator', navScanner: 'Scanner',
    themeLabel: 'Design', themeAuto: 'Auto', themeLight: 'Hell', themeDark: 'Dunkel',
    langLabel: 'Sprache',

    heroTitle: 'QR liest sich gut.<br>Es war nur nie <strong>schön</strong>',
    heroLead: 'Plakate, Verpackungen, Visitenkarten — QR ist überall, und ein Schwarz-Weiß-Quadrat auf ein wochenlang gestaltetes Layout zu setzen, hat immer wehgetan. Doch QR sieht so aus, weil es so aussehen musste: So baut man einen Code, wenn <strong>eine Kamera und ein Prozessor von 1994</strong> ihn überhaupt lesen sollen.',
    heroLead2: 'Diese Beschränkungen sind weitgehend gefallen. Handykameras und Rechenleistung haben Luft. Statt allein der Erkennung nachzujagen, ist diese Luft hier darin gelandet, dass der Code <strong>sehenswert</strong> ist. Das ist kein Ersatz für QR — es ist <strong>ein Platz daneben</strong>. Das Ergebnis ist ein <strong>3D-Barcode</strong> — flach gedruckt, aber räumlich gelesen.',
    whyNowTitle: 'Warum jetzt',
    whyNow1: '<strong>QR war die richtige Antwort seiner Zeit.</strong> Zwei Werte, quadratische Module, große Suchmuster — jede dieser Entscheidungen gab es, damit auch eine schwache Kamera lesen konnte. Unter diesen Bedingungen war der Verzicht auf Ästhetik vernünftig.',
    whyNow2: '<strong>Diese Voraussetzung hat sich geändert.</strong> Heutige Handykameras sind damit nicht zu vergleichen, und Echtzeit-Videoverarbeitung läuft im Browser. Der gewonnene Spielraum konnte in Dichte fließen — oder in <strong>das Aussehen</strong>. Deshalb gibt es dieses Format.',
    whyNow3: '<strong>Dafür wurde die Dichte aufgegeben.</strong> Rautenzellen nutzen die Fläche schlechter als quadratische Module. Dieses Format tritt nicht im Wettbewerb um Dichte an. Wer viel unterbringen muss, ist mit QR richtig.',
    ctaMake: 'Code erstellen',

    typesTitle: 'Fünf Typen',
    typesLead: 'Wählen Sie danach, wo der Code sitzen soll. Alle fünf teilen denselben Datenvertrag und unterscheiden sich nur in der Silhouette. Jeder Code unten enthält <code>https://tl.estre.so</code>.',
    typeYName: 'Type Y — einzelner Würfel',
    typeYDesc: 'Drei n×n-Flächen. Ein geschlossenes Zeichen, gut für Beschilderung und Merchandise.',
    typeYMeta: 'n = 13 / 21 / 25 · Nutzdaten netto 31 / 98 / 141 B',
    typeOName: 'Type O — Sechseckfeld',
    typeODesc: 'Die Grundform. Rautenzellen legen sich um ein zentrales Suchmuster nach außen.',
    typeOMeta: 'k = 6 / 8 / 10 / 12 · Nutzdaten netto 18 / 39 / 65 / 97 B',
    typeCName: 'Type C — ultrahohe Kapazität mit Kerbe',
    typeCDesc: 'Die Kerbe auf 3 Uhr legt Ausrichtung und Typ schon in der Silhouette fest. C0–C3 sind für Scans im Nahbereich gedacht; ab C1 holen Sie den Code näher heran oder vergrößern ihn.',
    typeCMeta: 'k = 14 / 16 / 18 / 20 · Netto-Nutzlast 130 / 172 / 220 / 255 B',
    typeAName: 'Type A — dreieckige Silhouette',
    typeADesc: 'Ein sechseckiger Kern plus Eckflächen ergibt ein gleichseitiges Dreieck.',
    typeAMeta: 'k = 6 / 8 / 10 / 12 · Nutzdaten netto 31 / 62 / 101 B',
    typeKName: 'Type K — Hexagramm',
    typeKDesc: 'Ein Dreieck vereinigt mit seinem 180°-Bild. Größte Nutzlast bei gleichem k.',
    typeKMeta: 'k = 6 / 8 / 10 / 12 · Netto-Nutzlast 43 / 86 / 138 B',
    typesFoot: 'Die Netto-Nutzdaten gelten für ECC-M. Alle fünf Typen können einen <strong>Ersatz-QR</strong> danebentragen, sodass ein Weg bleibt, wo ein TL-Code nicht gelesen werden kann.',

    howTitle: 'Funktionsweise',
    how1Title: '1. Zelle = drei Rauten', how1Desc: 'Eine Rhombille-Parkettierung teilt jede sechseckige Zelle in die Flächen T, L und R.',
    how2Title: '2. Reihenfolge = Symbol', how2Desc: 'Das Ordnen der drei Luminanzen ergibt 3! = 6 Fälle — eine Ziffer zur Basis 6.',
    how3Title: '3. 3 Ziffern = 1 Symbol', how3Desc: 'Reed–Solomon über dem Primkörper GF(211) korrigiert Fehler.',
    whyTitle: 'Was dadurch frei wird',
    why1: '<strong>Invariant gegenüber monotonen Transformationen.</strong> Globale Lichtwechsel, Gamma und die Tonwertabbildung eines Druckers sind monoton — sie können eine Reihenfolge nicht umstellen. Überlebt die Reihenfolge, überlebt der Wert.',
    why2: '<strong>Das Rendering bleibt frei.</strong> Der Datenvertrag lautet nur „die Reihenfolge zwischen den Flächen plus ein Mindestabstand“. Darin sind Farbe, Textur, Verläufe je Fläche und Animation offen. Genau diese Freiheit ist der Sinn des Formats.',
    why3: '<strong>Schön wird davon aber nichts von allein.</strong> Frei wird der Vertrag, nicht das Ergebnis. Was Sie darin zeichnen, bleibt Ihre Arbeit.',

    statusTitle: 'Scanner — Stand der Dinge',
    statusLead: '<strong>Der Decoder funktioniert.</strong> Alle vier Typen werden auf Fotos echter Geräte gelesen; offen sind Genauigkeit und Tempo. Jede Zeit unten ist <strong>eine Dekodierung eines Standfotos von einem echten Telefon</strong> — weder die Zeit bis zum ersten Treffer noch eine Erfolgsquote im Livebetrieb.',
    thType: 'Typ', thDecoded: 'Echte Fotos dekodiert', thTime: 'Eine Dekodierung, Standfoto', thRealtime: 'Live-Prüfung',
    rowYName: '<strong>Type Y</strong> — einzelner Würfel',
    rowOName: '<strong>Type O</strong> — Sechseckfeld',
    rowAName: '<strong>Type A</strong> — dreieckige Silhouette',
    rowKName: '<strong>Type K</strong> — Hexagramm',
    rowCenterQr: `<strong>Zentrale-QR-Variante</strong> (alle vier Typen) · ${stats.centerQr.measuredOn}`,
    badgePending: 'weitere Messungen nötig',
    statusNote1: '<strong>Die Zeit einer Dekodierung auf einem Standfoto sagt nichts darüber, wie sich Live-Scannen anfühlt.</strong> In der ersten Messreihe auf einem echten Gerät konnte ein schnelles Einzelbild trotzdem zu einem späten ersten Treffer führen, wenn viele Bilder nötig waren, und die Reihenfolge der Typen wich von dieser Standfoto-Tabelle ab. Diese Reihe umfasst ein Gerät und eine kleine Stichprobe — deshalb vergeben wir noch keine Live-Bewertung.',
    statusNote0: `<strong>Eine Dekodierung eines Standbilds.</strong> Type O ist jetzt am schnellsten; A, K und Y liegen dicht dahinter. ⚠ Eine frühere Fassung dieser Seite nannte Type Y als schnellsten — das war eine Stichprobe von 9 Fotos, und bei größerer Stichprobe hat sich die <strong>Reihenfolge umgedreht</strong>. Lesen Sie das nicht als Live-Zeit bis zum ersten Treffer.`,
    statusNote2: `Auch die Aufnahmebedingungen wirken stark. Gemessen war <strong>${stats.cellFloorPx} Pixel je Zelle</strong> die Untergrenze der Dekodierung, und bei gleichem Abstand fasst ein <strong>Ultraweitwinkel</strong> den Code kleiner und fällt unter diese Linie (Ultraweitwinkel ${stats.ultraWideFailPx} px gescheitert / Weitwinkel ${stats.wideOkPx} px erfolgreich). Deshalb bietet der Scanner eine Objektivwahl an.`,
    statusNote3: 'In der <strong>Variante mit zentralem QR</strong> ersetzt ein QR-Block das zentrale Suchmuster. Dessen Suchmuster liefern den Einstieg für Position und Ausrichtung, mit dem der umgebende TL-Körper dekodiert wird. Der Generator nutzt diesen geprüften Weg jetzt standardmäßig für die Typen O und A. Standardmäßig bleibt der QR ein Ersatz mit einem Leser-Link; die Nutzdaten selbst bleiben im TL-Körper.',
    statusFoot: `Gemessen am ${stats.measuredOn} · Stichprobe von <strong>${stats.sampleCount} Fotos</strong> (jedes bei ${stats.triedShortSides} px kurzer Seite versucht). ⚠ Der Großteil der Stichprobe ist <strong>vom Monitor abfotografiert</strong> — das sind keine Druck- oder Vor-Ort-Werte. Und ${stats.probeExcluded} der ${stats.corpusTotal} Korpusbilder sind Grenz- und Versuchsaufnahmen, die gerade deshalb aufbewahrt werden, weil sie noch nicht dekodieren — sie sind hier ausgeschlossen. Nur die Zentral-QR-Zeile stammt aus der älteren Runde vom ${stats.centerQr.measuredOn}.`,

    specTitle: 'Spezifikation und Implementierung',
    spec1: 'Formatspezifikation und Referenzimplementierung sind unter der <strong>Apache License 2.0</strong> veröffentlicht. Reines JavaScript, keine Build-Toolchain, null Laufzeitabhängigkeiten — es läuft als einzelne HTML-Datei.',
    spec2: '<strong>Nur den Decoder zu implementieren gilt bereits als konforme Implementierung.</strong> Verbreitung beginnt auf der Leseseite.',
    ctaSpec: 'Spezifikation lesen', ctaImpl: 'Referenzimplementierung',
    thSite: 'Site', thRole: 'Rolle', thState: 'Status',
    roleGenerator: 'Generator', roleScanner: 'Scanner', roleHub: 'Übersichtsseite',
    stateWorking: 'aktiv', stateHere: 'Sie sind hier', stateScanner: 'aktiv — Stand ›',
    footerTrademark: 'QR Code is a registered trademark of DENSO WAVE INCORPORATED.',
    footerCopyright: '© 2026 SoliEstre — TrilLuminance (cube) · Codename Trilume',
  },

  /* es — usted (3인칭 단수 명령/직설). */
  es: {
    title: 'TLcube — un código de barras 3D (en realidad 2.5D) que lleva los datos en el rango de luminancia',
    description: 'Un código de barras 3D abierto que divide una celda hexagonal en tres caras romboidales y lleva los datos en el orden de luminancia relativa de esas caras. La especificación y la implementación de referencia se publican bajo Apache-2.0.',
    ogTitle: 'TLcube — un código de barras 3D que lleva los datos en el rango de luminancia',
    ogDescription: 'Los datos viajan en el orden de las tres caras, no en el brillo absoluto. Mientras el orden sobreviva, el valor sobrevive.',
    ogImageAlt: 'Banner de TLcube — un código cubo Type Y verde junto a los códigos Type O, A y K.',
    jsonHeadline: 'TLcube — un código de barras 3D que lleva los datos en el rango, no en el brillo absoluto',
    jsonDescription: 'Un código de barras 3D abierto que divide una celda hexagonal en tres caras romboidales y usa su orden de luminancia relativa (3! = 6) como un símbolo en base 6. Invariante ante transformaciones tonales monótonas.',

    navWhyNow: 'Por qué ahora',
    navWhat: 'Cómo funciona', navTypes: 'Tipos', navStatus: 'Estado del escáner', navSpec: 'Especificación',
    navGenerator: 'Generador', navScanner: 'Escáner',
    themeLabel: 'Tema', themeAuto: 'Auto', themeLight: 'Claro', themeDark: 'Oscuro',
    langLabel: 'Idioma',

    heroTitle: 'El QR se lee bien.<br>Solo que nunca ha sido <strong>bonito</strong>',
    heroLead: 'Carteles, envases, tarjetas de visita — el QR está en todas partes, y colocar un cuadrado en blanco y negro sobre un diseño trabajado durante semanas siempre ha dolido. Pero el QR tiene ese aspecto por una razón: es lo que se construye cuando <strong>una cámara y un procesador de 1994</strong> tienen que poder leerlo.',
    heroLead2: 'Esas restricciones se han levantado en buena parte. Las cámaras de los teléfonos y la potencia de cálculo van sobradas. Así que, en lugar de perseguir solo el reconocimiento, ese margen se ha gastado en que <strong>merezca la pena mirarlo</strong>. No es un sustituto del QR: es <strong>un asiento a su lado</strong>. El resultado es un <strong>código de barras 3D</strong> — impreso en plano, pero percibido en relieve.',
    whyNowTitle: 'Por qué ahora',
    whyNow1: '<strong>El QR fue la respuesta correcta para su momento.</strong> Dos valores, módulos cuadrados, patrones localizadores grandes — cada una de esas decisiones existía para que una cámara débil pudiera leerlo igualmente. Con esas restricciones, renunciar a la estética era razonable.',
    whyNow2: '<strong>Esa premisa ha cambiado.</strong> Las cámaras de los teléfonos de hoy no se parecen en nada a aquellas, y el procesado de vídeo en tiempo real corre dentro de un navegador. Ese margen podía ir a la densidad — o podía ir a <strong>cómo se ve</strong>. Por eso existe este formato.',
    whyNow3: '<strong>A cambio se renunció a la densidad.</strong> Las celdas romboidales aprovechan peor la superficie que los módulos cuadrados. Este formato no compite en densidad. Si hay que llevar mucho, la herramienta adecuada es el QR.',
    ctaMake: 'Crear un código',

    typesTitle: 'Cinco tipos',
    typesLead: 'Elija según dónde vaya a ir. Los cinco comparten el mismo contrato de datos y solo se diferencian en la silueta. Todos los códigos de abajo contienen <code>https://tl.estre.so</code>.',
    typeYName: 'Type Y — cubo único',
    typeYDesc: 'Tres caras n×n. Una marca de una sola pieza, buena para rotulación y merchandising.',
    typeYMeta: 'n = 13 / 21 / 25 · carga útil neta 31 / 98 / 141 B',
    typeOName: 'Type O — campo hexagonal',
    typeODesc: 'La forma base. Las celdas romboidales se extienden alrededor de un patrón localizador central.',
    typeOMeta: 'k = 6 / 8 / 10 / 12 · carga útil neta 18 / 39 / 65 / 97 B',
    typeCName: 'Type C — capacidad ultra con muesca',
    typeCDesc: 'La muesca de las 3 fija la orientación y el tipo en la propia silueta. La gama C0–C3 es para escaneo a corta distancia; desde C1, acerque el código o use el zoom.',
    typeCMeta: 'k = 14 / 16 / 18 / 20 · carga útil neta 130 / 172 / 220 / 255 B',
    typeAName: 'Type A — silueta triangular',
    typeADesc: 'Un núcleo hexagonal más parches de esquina, que forman un triángulo equilátero.',
    typeAMeta: 'k = 6 / 8 / 10 / 12 · carga útil neta 31 / 62 / 101 B',
    typeKName: 'Type K — Hexagrama',
    typeKDesc: 'Un triángulo unido con su imagen a 180°. Mayor carga útil con la misma k.',
    typeKMeta: 'k = 6 / 8 / 10 / 12 · carga útil neta 43 / 86 / 138 B',
    typesFoot: 'La carga útil neta es con ECC-M. Los cinco tipos pueden llevar al lado un <strong>QR de respaldo</strong>, de modo que quede una vía donde un código TL no se pueda leer.',

    howTitle: 'Cómo funciona',
    how1Title: '1. Celda = tres rombos', how1Desc: 'Un teselado rhombille divide cada celda hexagonal en las caras T, L y R.',
    how2Title: '2. Orden = símbolo', how2Desc: 'Ordenar las tres luminancias da 3! = 6 resultados — un dígito en base 6.',
    how3Title: '3. 3 dígitos = 1 símbolo', how3Desc: 'Reed–Solomon sobre el cuerpo primo GF(211) corrige los errores.',
    whyTitle: 'Qué se libera',
    why1: '<strong>Invariante ante transformaciones monótonas.</strong> Los cambios de iluminación global, el gamma y el mapeo tonal de una impresora son monótonos: no pueden alterar un orden. Si el orden sobrevive, el valor sobrevive.',
    why2: '<strong>El renderizador queda libre.</strong> El contrato de datos es solo «el orden entre las caras, más una separación mínima». Dentro de eso, el color, la textura, los degradados por cara y la animación están abiertos. Esa libertad es el sentido del formato.',
    why3: '<strong>Pero nada se vuelve bonito por sí solo.</strong> Lo que se abre es el contrato, no el resultado. Lo que dibuje dentro sigue siendo su trabajo.',

    statusTitle: 'Escáner — dónde estamos',
    statusLead: '<strong>El decodificador funciona.</strong> Los cuatro tipos se leen en fotos de dispositivos reales; queda subir la precisión y la velocidad. Cada tiempo de abajo es <strong>una decodificación de una foto fija tomada con un teléfono real</strong>, no el tiempo hasta el primer enganche ni una tasa de acierto en directo.',
    thType: 'Tipo', thDecoded: 'Fotos reales decodificadas', thTime: 'Una decodificación en foto fija', thRealtime: 'Validación en directo',
    rowYName: '<strong>Type Y</strong> — cubo único',
    rowOName: '<strong>Type O</strong> — campo hexagonal',
    rowAName: '<strong>Type A</strong> — silueta triangular',
    rowKName: '<strong>Type K</strong> — hexagrama',
    rowCenterQr: `<strong>Variante QR central</strong> (los cuatro tipos) · ${stats.centerQr.measuredOn}`,
    badgePending: 'faltan más medidas',
    statusNote1: '<strong>El tiempo de una decodificación en foto fija no predice cómo se siente el escaneo en directo.</strong> En las primeras medidas sobre un dispositivo real, un fotograma rápido podía dar aun así un primer enganche lento cuando hacían falta muchos fotogramas antes de uno acertado, y el orden de los tipos difería de esta tabla de foto fija. Esa traza cubre un solo dispositivo y una muestra pequeña, así que todavía no asignamos una nota de uso en directo.',
    statusNote0: `<strong>Una decodificación de una sola foto fija.</strong> Ahora el Type O es el más rápido; A, K e Y quedan cerca detrás. ⚠ Una versión anterior de esta página decía que el Type Y era el más rápido: era una muestra de 9 fotos y, con una muestra más amplia, el <strong>orden se invirtió</strong>. No lea esto como tiempo de primer enganche en vivo.`,
    statusNote2: `Las condiciones de captura también pesan. En la medición, <strong>${stats.cellFloorPx} píxeles por celda</strong> fue el suelo de decodificación y, a la misma distancia, un <strong>objetivo ultra gran angular</strong> encuadra el código más pequeño y baja de esa línea (ultra gran angular ${stats.ultraWideFailPx} px falló / gran angular ${stats.wideOkPx} px acertó). Por eso el escáner ofrece un selector de objetivo.`,
    statusNote3: 'En la <strong>variante de QR central</strong>, un bloque QR sustituye al patrón localizador central. Sus patrones aportan el punto de entrada de posición y orientación con el que se decodifica el cuerpo TL de alrededor. El generador usa ya esta vía validada de forma predeterminada para los tipos O y A. Por defecto el QR sigue siendo un respaldo con un enlace al lector; la carga útil se queda en el cuerpo TL.',
    statusFoot: `Medido el ${stats.measuredOn} · muestra de <strong>${stats.sampleCount} fotos</strong> (cada una probada a ${stats.triedShortSides} px de lado corto). ⚠ La mayor parte de la muestra está <strong>fotografiada de una pantalla</strong>: no son cifras de impresión ni de colocación real. Además, ${stats.probeExcluded} de los ${stats.corpusTotal} fotogramas del corpus son tomas límite guardadas precisamente porque todavía no decodifican — aquí quedan excluidas. Solo la fila de QR central viene de la ronda anterior del ${stats.centerQr.measuredOn}.`,

    specTitle: 'Especificación e implementación',
    spec1: 'La especificación del formato y la implementación de referencia se publican bajo la <strong>Licencia Apache 2.0</strong>. JavaScript puro, sin cadena de compilación, cero dependencias en ejecución — funciona como un único archivo HTML.',
    spec2: '<strong>Implementar solo el decodificador ya cuenta como implementación conforme.</strong> La adopción empieza por el lado que lee.',
    ctaSpec: 'Leer la especificación', ctaImpl: 'Implementación de referencia',
    thSite: 'Sitio', thRole: 'Función', thState: 'Estado',
    roleGenerator: 'Generador', roleScanner: 'Escáner', roleHub: 'Sitio de presentación',
    stateWorking: 'activo', stateHere: 'está aquí', stateScanner: 'activo — estado ›',
    footerTrademark: 'QR Code is a registered trademark of DENSO WAVE INCORPORATED.',
    footerCopyright: '© 2026 SoliEstre — TrilLuminance (cube) · nombre en clave Trilume',
  },

  /* pt — pt-PT 어휘 (ecrã·câmara·ficheiro·predefinição). 스캐너 사전과 같은 계열. */
  pt: {
    title: 'TLcube — um código de barras 3D (na verdade 2.5D) que leva os dados na ordem de luminância',
    description: 'Um código de barras 3D aberto que divide uma célula hexagonal em três faces em losango e leva os dados na ordem de luminância relativa dessas faces. A especificação e a implementação de referência estão publicadas sob Apache-2.0.',
    ogTitle: 'TLcube — um código de barras 3D que leva os dados na ordem de luminância',
    ogDescription: 'Os dados assentam na ordem das três faces, não no brilho absoluto. Enquanto a ordem sobreviver, o valor sobrevive.',
    ogImageAlt: 'Banner TLcube — um código cubo Type Y verde ao lado dos códigos Type O, A e K.',
    jsonHeadline: 'TLcube — um código de barras 3D que leva os dados na ordem, não no brilho absoluto',
    jsonDescription: 'Um código de barras 3D aberto que divide uma célula hexagonal em três faces em losango e usa a sua ordem de luminância relativa (3! = 6) como um símbolo em base 6. Invariante a transformações tonais monótonas.',

    navWhyNow: 'Porquê agora',
    navWhat: 'Como funciona', navTypes: 'Tipos', navStatus: 'Estado do scanner', navSpec: 'Especificação',
    navGenerator: 'Gerador', navScanner: 'Scanner',
    themeLabel: 'Tema', themeAuto: 'Auto', themeLight: 'Claro', themeDark: 'Escuro',
    langLabel: 'Idioma',

    heroTitle: 'O QR lê-se bem.<br>Só nunca foi <strong>bonito</strong>',
    heroLead: 'Cartazes, embalagens, cartões de visita — o QR está em todo o lado, e pousar um quadrado a preto e branco sobre um design trabalhado durante semanas sempre custou. Mas o QR tem este aspeto por uma razão: é o que se constrói quando <strong>uma câmara e um processador de 1994</strong> têm de conseguir lê-lo.',
    heroLead2: 'Essas restrições caíram em grande parte. As câmaras dos telemóveis e o poder de cálculo têm folga. Por isso, em vez de perseguir apenas o reconhecimento, essa folga foi gasta em <strong>valer a pena olhar</strong>. Não é um substituto do QR: é <strong>um lugar ao lado</strong>. O resultado é um <strong>código de barras 3D</strong> — impresso em plano, mas percebido em relevo.',
    whyNowTitle: 'Porquê agora',
    whyNow1: '<strong>O QR foi a resposta certa para o seu tempo.</strong> Dois valores, módulos quadrados, padrões localizadores grandes — cada uma dessas escolhas existia para que mesmo uma câmara fraca conseguisse ler. Com essas restrições, abdicar da estética era racional.',
    whyNow2: '<strong>Essa premissa mudou.</strong> As câmaras dos telemóveis de hoje não se comparam, e o processamento de vídeo em tempo real corre dentro de um navegador. Essa folga podia ir para a densidade — ou podia ir para <strong>o aspeto</strong>. É por isso que este formato existe.',
    whyNow3: '<strong>Em troca, abdicou-se da densidade.</strong> As células em losango aproveitam pior a área do que os módulos quadrados. Este formato não compete em densidade. Se for preciso levar muito, a ferramenta certa é o QR.',
    ctaMake: 'Criar um código',

    typesTitle: 'Cinco tipos',
    typesLead: 'Escolha consoante o sítio onde vai ficar. Os cinco partilham o mesmo contrato de dados e diferem apenas na silhueta. Todos os códigos abaixo contêm <code>https://tl.estre.so</code>.',
    typeYName: 'Type Y — cubo único',
    typeYDesc: 'Três faces n×n. Uma marca de uma só peça, boa para sinalética e merchandising.',
    typeYMeta: 'n = 13 / 21 / 25 · carga útil líquida 31 / 98 / 141 B',
    typeOName: 'Type O — campo hexagonal',
    typeODesc: 'A forma base. As células em losango estendem-se à volta de um padrão localizador central.',
    typeOMeta: 'k = 6 / 8 / 10 / 12 · carga útil líquida 18 / 39 / 65 / 97 B',
    typeCName: 'Type C — capacidade ultra com entalhe',
    typeCDesc: 'O entalhe das 3 horas fixa a orientação e o tipo na própria silhueta. A gama C0–C3 destina-se a leitura de perto; a partir de C1, aproxime o código ou amplie a imagem.',
    typeCMeta: 'k = 14 / 16 / 18 / 20 · carga útil líquida 130 / 172 / 220 / 255 B',
    typeAName: 'Type A — silhueta triangular',
    typeADesc: 'Um núcleo hexagonal mais remendos de canto, formando um triângulo equilátero.',
    typeAMeta: 'k = 6 / 8 / 10 / 12 · carga útil líquida 31 / 62 / 101 B',
    typeKName: 'Type K — Hexagrama',
    typeKDesc: 'Um triângulo unido à sua imagem de 180°. Maior carga útil com o mesmo k.',
    typeKMeta: 'k = 6 / 8 / 10 / 12 · carga útil líquida 43 / 86 / 138 B',
    typesFoot: 'A carga útil líquida é para ECC-M. Os cinco tipos podem levar ao lado um <strong>QR de reserva</strong>, de modo que reste um caminho onde um código TL não possa ser lido.',

    howTitle: 'Como funciona',
    how1Title: '1. Célula = três losangos', how1Desc: 'Uma pavimentação rhombille divide cada célula hexagonal nas faces T, L e R.',
    how2Title: '2. Ordem = símbolo', how2Desc: 'Ordenar as três luminâncias dá 3! = 6 resultados — um dígito em base 6.',
    how3Title: '3. 3 dígitos = 1 símbolo', how3Desc: 'Reed–Solomon sobre o corpo primo GF(211) corrige os erros.',
    whyTitle: 'O que isto liberta',
    why1: '<strong>Invariante a transformações monótonas.</strong> As variações de iluminação global, o gama e o mapeamento tonal de uma impressora são monótonos: não conseguem trocar uma ordem. Se a ordem sobrevive, o valor sobrevive.',
    why2: '<strong>O renderizador fica livre.</strong> O contrato de dados é apenas «a ordem entre as faces, mais uma separação mínima». Dentro disso, a cor, a textura, os gradientes por face e a animação estão todos abertos. É essa liberdade que dá sentido ao formato.',
    why3: '<strong>Mas nada fica bonito sozinho.</strong> O que se abre é o contrato, não o resultado. O que desenhar lá dentro continua a ser trabalho seu.',

    statusTitle: 'Scanner — ponto de situação',
    statusLead: '<strong>O descodificador funciona.</strong> Os quatro tipos leem-se a partir de fotos de dispositivos reais; falta subir a precisão e a velocidade. Cada tempo abaixo é <strong>uma descodificação de uma foto fixa tirada com um telemóvel real</strong>, não o tempo até à primeira fixação nem uma taxa de êxito ao vivo.',
    thType: 'Tipo', thDecoded: 'Fotos reais descodificadas', thTime: 'Uma descodificação em foto fixa', thRealtime: 'Validação ao vivo',
    rowYName: '<strong>Type Y</strong> — cubo único',
    rowOName: '<strong>Type O</strong> — campo hexagonal',
    rowAName: '<strong>Type A</strong> — silhueta triangular',
    rowKName: '<strong>Type K</strong> — hexagrama',
    rowCenterQr: `<strong>Variante QR central</strong> (os quatro tipos) · ${stats.centerQr.measuredOn}`,
    badgePending: 'faltam mais medições',
    statusNote1: '<strong>O tempo de uma descodificação em foto fixa não prevê a sensação da leitura ao vivo.</strong> Nas primeiras medições em dispositivo real, um fotograma rápido podia ainda assim dar uma primeira fixação lenta quando eram precisos muitos fotogramas antes de um bem-sucedido, e a ordem dos tipos diferia desta tabela de foto fixa. Esse registo abrange um só dispositivo e uma amostra pequena, pelo que ainda não atribuímos uma classificação de uso ao vivo.',
    statusNote0: `<strong>Uma descodificação de uma única foto fixa.</strong> O Type O é agora o mais rápido; A, K e Y ficam próximos atrás. ⚠ Uma versão anterior desta página dizia que o Type Y era o mais rápido: era uma amostra de 9 fotos e, com uma amostra mais ampla, a <strong>ordem inverteu-se</strong>. Não leia isto como tempo de primeiro engate em direto.`,
    statusNote2: `As condições de captura também pesam. Na medição, <strong>${stats.cellFloorPx} píxeis por célula</strong> foi o limite inferior de descodificação e, à mesma distância, uma <strong>objetiva ultra grande-angular</strong> enquadra o código mais pequeno e desce abaixo dessa linha (ultra grande-angular ${stats.ultraWideFailPx} px falhou / grande-angular ${stats.wideOkPx} px conseguiu). É por isso que o scanner oferece a escolha da objetiva.`,
    statusNote3: 'Na <strong>variante de QR central</strong>, um bloco QR substitui o padrão localizador central. Os seus padrões dão o ponto de entrada de posição e orientação com que se descodifica o corpo TL em redor. O gerador usa agora este caminho validado por predefinição nos tipos O e A. Por predefinição, o QR continua a ser uma reserva com uma ligação para o leitor; a carga útil fica no corpo TL.',
    statusFoot: `Medido a ${stats.measuredOn} · amostra de <strong>${stats.sampleCount} fotos</strong> (cada uma tentada a ${stats.triedShortSides} px de lado curto). ⚠ A maior parte da amostra está <strong>fotografada a partir de um ecrã</strong>: não são números de impressão nem de colocação real. Além disso, ${stats.probeExcluded} dos ${stats.corpusTotal} fotogramas do corpus são capturas-limite guardadas precisamente por ainda não descodificarem — ficam aqui excluídas. Só a linha do QR central vem da ronda anterior de ${stats.centerQr.measuredOn}.`,

    specTitle: 'Especificação e implementação',
    spec1: 'A especificação do formato e a implementação de referência estão publicadas sob a <strong>Licença Apache 2.0</strong>. JavaScript simples, sem cadeia de compilação, zero dependências em execução — funciona como um único ficheiro HTML.',
    spec2: '<strong>Implementar apenas o descodificador já conta como implementação conforme.</strong> A adoção começa pelo lado que lê.',
    ctaSpec: 'Ler a especificação', ctaImpl: 'Implementação de referência',
    thSite: 'Site', thRole: 'Papel', thState: 'Estado',
    roleGenerator: 'Gerador', roleScanner: 'Scanner', roleHub: 'Site de apresentação',
    stateWorking: 'ativo', stateHere: 'está aqui', stateScanner: 'ativo — estado ›',
    footerTrademark: 'QR Code is a registered trademark of DENSO WAVE INCORPORATED.',
    footerCopyright: '© 2026 SoliEstre — TrilLuminance (cube) · nome de código Trilume',
  },
};
